### ISSUE TITLE
Update to latest version 

### ISSUE THREAD

**Issue by Marshallcoolman** [SIsilicon/WorldEdit-BE#10]
Does not work on latest version. It won’t install on the latest version of minecraft and gives me a version error, could you update it soon?

**Comment by Marshallcoolman** [comment]
> Did you have another version of the addon already installed?

Not really sure how to reply on here so I hope this works. When I try to install it I get an error. I have not used this before and have no other add ons installed.

**Comment by SIsilicon** [comment]
Could you show a video of you attempting to install it? I don't seem to have any problems installing it myself.

**Comment by Marshallcoolman** [comment]
> Could you show a video of you attempting to install it? I don't seem to have any problems installing it myself.

Fixed it. Thanks for your help this is an awesome addon.

**Comment by SIsilicon** [comment]
Could you tell me how you got it working? In case anyone else has this problem.
