### ISSUE TITLE
[REQUEST]No current way to set to spruce log

### ISSUE THREAD

**Issue by IronVader6** [SIsilicon/WorldEdit-BE#101]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Problem

When doing /give on a block or /fill on a block you can add data so you can do /give @s log 1 1 the first 1 will give you 1 item but the second 1 would make the log spruce instead of oak 

### Proposed Solution

which i would like to do ;walls log 1 or ;walls spruce_log so i can set things to logs or make it so that you can use ids so i could do /walls 17 which would be spruce

### Alternatives

The only current work around is using /fill or doing it manually

### Additional info

![image](https://user-images.githubusercontent.com/82355134/179339729-5b4677f1-f52f-4b98-a133-c1c3c9e35d3a.png)
![image](https://user-images.githubusercontent.com/82355134/179339756-47bf2c97-9982-4f40-9a80-b2de73837b25.png)

**Comment by SIsilicon** [comment]
When doing data values with WorldEdit, you must add a colon between the block and number. `block:data`
