### ISSUE TITLE
Item Description 

### ISSUE THREAD

**Issue by ArtemInMinus** [SIsilicon/WorldEdit-BE#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Hi all! I noticed that with a set of parameters, WorldEditBE is not displayed in the inventory on a certain item or block "can_place_on" and "can_destroy_on" can be placed on and can be broken, please fix it!

### Expected behaviour

Hi all! I noticed that with a set of parameters, WorldEditBE is not displayed in the inventory on a certain item or block "can_place_on" and "can_destroy_on" can be placed on and can be broken, please fix it!

### Minecraft version

1.19.11

### Additional info

Hi all! I noticed that with a set of parameters, WorldEditBE is not displayed in the inventory on a certain item or block "can_place_on" and "can_destroy_on" can be placed on and can be broken, please fix it!

**Comment by SIsilicon** [comment]
Inferior version of https://github.com/SIsilicon/WorldEdit-BE/issues/104
