### ISSUE TITLE
Error in item description

### ISSUE THREAD

**Issue by ArtemInMinus** [SIsilicon/WorldEdit-BE#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When I turned on the set of parameters (editor note: behaviour pack), the "can_place_on" and "can_destroy_on" components were no longer displayed in the item, so you can set and break

### Expected behaviour

It should be displayed in the description of the item, please fix it

### Minecraft version

1.19.11

**Comment by SIsilicon** [comment]
Could you be more specific? What are "the set of parameters"?

**Comment by ArtemInMinus** [comment]
> Could you be more specific? What are "the set of parameters"?

Behavior Pack

**Comment by SIsilicon** [comment]
The tags still work. You just can't see them. The addon hides those tags by default since they're used by the settings items.

**Comment by ArtemInMinus** [comment]
> The tags still work. You just can't see them. The addon hides those tags by default since they're used by the settings items. You can show them again with `/gamerule showTags true` I think.

and you can remove it, well, so that it is displayed by default?
