### ISSUE TITLE
1.19.20 incompatibility

### ISSUE THREAD

**Issue by Gamecat178** [SIsilicon/WorldEdit-BE#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

when on a realm on  "watchdog" stops the realm

### Expected behaviour

it works and nothing goes wrong

### Steps to reproduce

join a realm with the worldedit applied 
try moving/rotating something large

### Minecraft version

1.19.20

### Device and operating system

Win 11

### Additional info

![image](https://user-images.githubusercontent.com/97407708/184069270-b300ad66-1541-4bc7-92b1-8a140cf163bf.png)
![image](https://user-images.githubusercontent.com/97407708/184069350-e1f04dca-4030-4bf5-b698-393c561e2cf5.png)

**Comment by Gamecat178** [comment]
most commonly happens when pasting

**Comment by SIsilicon** [comment]
fixed by https://github.com/SIsilicon/WorldEdit-BE/pull/107.
