### ISSUE TITLE
If you use ;stack or ;move a lot and when you come out, the game crashes.

### ISSUE THREAD

**Issue by wow1972** [SIsilicon/WorldEdit-BE#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

After that, you will not be able to access the game.

### Expected behaviour

You should be able to connect to the world normally.

### Minecraft version

1.19.2

### Device and operating system

Android

**Comment by SIsilicon** [comment]
Does the game say something about a hang or "watchdog"?

**Comment by wow1972** [comment]
> 게임이 중단 또는 "감시 장치"에 대해 말합니까?

no

**Comment by wow1972** [comment]
Minecraft crashes.

**Comment by wow1972** [comment]
And you can't reconnect to that world.

**Comment by SIsilicon** [comment]
@wow1972 You're going to have to show a video of it happening for better context.

**Comment by wow1972** [comment]
It seems to occur in worlds that have been reinstalled after deleting WorldEdit.

**Comment by wow1972** [comment]
world_behavior_pack,
world_behavior_pack_history,
world_resource_pack,
world_resource_pack_history file and
I deleted the file in the behavior_pack ,resource_pack folder and reinstalled it

**Comment by wow1972** [comment]
And I couldn't take a video because I deleted the world where the problem occurred.

**Comment by SIsilicon** [comment]
Closing for now then.
