### ISSUE TITLE
Increase maximum region size

### ISSUE THREAD

**Issue by Marshallcoolman** [SIsilicon/WorldEdit-BE#11]
Could you give me instructions on how to increase the maximum region size? I have a really good PC and I am trying to work on a big project.

**Comment by SIsilicon** [comment]
The size limit is due to the nature of structure blocks in Minecraft. I have a solution in mind to remove this limit, but it will be a while until it's actually implemented.

**Comment by SIsilicon** [comment]
The only work around for now would be to do all your operations in pieces.

**Comment by Marshallcoolman** [comment]
ok thanks

**Comment by SIsilicon** [comment]
This has been implemented in the next release. 0.2.0
