### ISSUE TITLE
Watchdog exception when opening world

### ISSUE THREAD

**Issue by DavidManaia** [SIsilicon/WorldEdit-BE#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

So, i did get this error, i hit the Play button to play it because i'm building a city and i get this error when it's loading, It says "The server shut down due to an unhandled script watchdog exception."

Can i fix it? I don't what to see this error once again! OK?

### Expected behaviour

~~If this error happens once again, i still check for this Issue, OK?~~
The world should open as normal

### Minecraft version

1.19.30.23

### Device and operating system

Android

### Additional info

1. I don't use a server, i'm the builder to work on the city, but this error is stuck and there's no way to get out of this unless i remove the active addon from Resource Packs (World Edit Menu on Select World Screen in Main Menu), there, It loads like normal.
2. I use this mod for building my city and i don't what to delete this world and create a new world, OK?
3. And third is the developers who works on this mod explain to me how i can fix it, or instead the developers identify's this issue and then, it will fix it.

**Comment by SIsilicon** [comment]
Ok, did you check to see if this happens on other worlds too?

**Comment by DavidManaia** [comment]
> Ok, did you check to see if this happens on other worlds too?

I don't know this happens on other worlds, but i only use on one world, because of my city which is going to use this mod because i don't want my hands to be tired and also i can make this world faster, OK?

**Comment by SIsilicon** [comment]
> > Ok, did you check to see if this happens on other worlds too?
> 
> I don't know this happens on other worlds, but i only use on one world, because of my city which is going to use this mod because i don't want my hands to be tired and also i can make this world faster, OK?
> 
> Edit: Also i forgot to say that if i don't use the addon on my world, it loads without this error, having the addon on my world, of course, it causes the error.

We'll check to see if this error happens on other worlds.

**Comment by DavidManaia** [comment]
OK, so i did create a new world called TestWorld in order to test if i get the error and yes, i still getting that error.

What i did do to check and add:
• I checked the 2 options required to make the addon workable.
• I add the 2 addons, one is a Resource Pack and another was a Behavior Pack.

And no, It cannot load the world, why is this, your mod doesn't work in newer Beta versions of Minecraft BE (Bedrock Edition) or your mod has that issue on the original version of Minecraft BE?

**Comment by SIsilicon** [comment]
> OK, so i did create a new world called TestWorld in order to test if i get the error and yes, i still getting that error.
> 
> What i did do to check and add: • I checked the 2 options required to make the addon workable. • I add the 2 addons, one is a Resource Pack and another was a Behavior Pack.
> 
> And no, It cannot load the world, why is this, your mod doesn't work in newer Beta versions of Minecraft BE (Bedrock Edition) or your mod has that issue on the original version of Minecraft BE?

The addon works in the release version of Minecraft. And I just tested it in Minecraft Preview for Windows. It works fine there too. Maybe you could try reinstalling the game. Make sure to backup everything just in case.

**Comment by DavidManaia** [comment]
I reinstall the game everytime i will update it to a new version, however i did try:

• Cleaning data without deleting the com.mojang.minecraftpe in storage/emulated/0/Android/data folder.
• Cleaning cache, doesn't work.
• Deleting some temporary files in Minecraft: BE, for example: development_skin_packs folder, doesn't work.

I really don't know what it's happening to your mod, is your mod is working correctly and it simply doesn't work for me or your mod might have some issues loading, for me i cannot get past the watchdog exception error screen.

And one last thing, did you checked for your WorldEdit mod if there's some issues at all files that has caused this problem to happen and/or your WorldEdit mod has been need to be recomplied in order to fix this error?

**Comment by SIsilicon** [comment]
> I reinstall the game everytime i will update it to a new version

So you uninstall the app before updating?

> is your mod is working correctly and it simply doesn't work for me

It's not working for you. Like I said, it's working fine in both release and preview versions of the game.

You say that you reinstall everytime you update, but what I mean by that is to uninstall the game, then install it back.

**Comment by DavidManaia** [comment]
> So you uninstall the app before updating?
Yes, because it sometimes gives me error of "Application not installed", so i did to do this in order to not get this error.

> It's not working for you. Like I said, it's working fine in both release and preview versions of the game.

> You say that you reinstall everytime you update, but what I mean by that is to uninstall the game, then install it back.
Already said, i did to do it because otherwise i cannot update my game, OK?

**Comment by SIsilicon** [comment]
Did it act like this before you uninstalled the game?

**Comment by DavidManaia** [comment]
Yes, it did act even if i uninstall the game and reinstall it.

**Comment by SIsilicon** [comment]
What version of WorldEdit were you using?

**Comment by DavidManaia** [comment]
I'm using the latest version of WorldEdit.

**Comment by SIsilicon** [comment]
Which is

**Comment by DavidManaia** [comment]
0.6.4, i think is the latest version.

**Comment by SIsilicon** [comment]
Hmm. In the config file is an option to set the async time. Try setting it to a lower number like 50 and see if that helps.
See this docs page to know how to do that.
https://worldedit-be-docs.readthedocs.io/en/latest/configuration/#configuration

**Comment by DavidManaia** [comment]
I did set the async time to 50 and it didn't work, i did still get the watchdog exception error.

**Comment by SIsilicon** [comment]
Which Minecraft version did you start getting this error, and which one are you currently at?

**Comment by DavidManaia** [comment]
I start getting this since day before yesterday when i was having mod in Minecraft: BE 1.19.30.23, now, today, i'm currently on 1.19.30.25 and i still getting that error.

**Comment by SIsilicon** [comment]
It could be the beta itself on your end. You could downgrade to the latest release version of the game and see if it works then. Not on your current world, but a new one.

**Comment by DavidManaia** [comment]
> It could be the beta itself on your end. You could downgrade to the latest release version of the game and see if it works then. Not on your current world, but a new one.

I'm very sorry! I cannot use release versions, because i don't want to do it, I prefer to use the current beta version rather that the release versions, as i'm cannot do the downgrade, so i don't be able to use it (Only release versions of Minecraft), OK? Maybe this addon might now no longer working for me, maybe... I can find another WorldEdit mod that it works perfectly in the latest beta version of Minecraft: BE, OK? And i tired of this, i did said already that i did use TestWorld to see if works or not, but i know with the Create a World Tool in Minecraft: BE, it's not going to work, so i cannot do it, maybe i will see if there's another way to fix it or i can use another WorldEdit mod that it works very well or i can have nothing at all, OK?

**Comment by SIsilicon** [comment]
Closing as this seems to be a device isolated issue

**Comment by SIsilicon** [comment]
This issue has been properly resolved in 0.6.5.
