### ISSUE TITLE
Light gray concrete cannot be installed.

### ISSUE THREAD

**Issue by bum8844** [SIsilicon/WorldEdit-BE#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I used 'set' to use light gray concrete and copy and paste, the same result comes out

### Expected behaviour

but it didn't change, and only the message that the block was changed

### Steps to reproduce

1. Use ';set concrete[color=light_gray]' or ';copy' for light gray concrete and ';paste'
2. then you see that bug

### Minecraft version

1.19.2

### Device and operating system

Window 10

**Comment by SIsilicon** [comment]
`light_gray` is not a valid color property. You must mean `silver`.
