### ISSUE TITLE
It doesn't work for the new version v1.19.40

### ISSUE THREAD

**Issue by Jimnav-png** [SIsilicon/WorldEdit-BE#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

It just doesn't work anymore. I had the kit last time I logged out before the update, and now any of the tools work.
![image](https://user-images.githubusercontent.com/69730072/197880140-cd010b1e-5c53-4627-966e-be36a911c2e4.png)

Also, the GameTest Framework has now a different name:

![Captura de pantalla 2022-10-25 225141](https://user-images.githubusercontent.com/69730072/197879662-85e8d9ce-00e4-44b4-8fe1-268de42cbbff.png)
I don't know if that makes a difference

It shouldn't

### Expected behaviour

It should work
![Hola](https://user-images.githubusercontent.com/69730072/197881314-a4355e7c-ebad-4ccb-a740-87e69d4e93fc.png)

### Steps to reproduce

1. Update to v1.19.40
2. Open your world where the tool worked before
3. Try to use the tool
4. Fail

### Content logs

The Log GUI throws this error:
![image](https://user-images.githubusercontent.com/69730072/197879899-b6926b87-10be-4048-80be-4892e57513fb.png)

[Scripting][error]-Plugin server/index.js ran with error: ReferenceError: Module [mojang-minecraft] not found. Native module error or file not found.

### Minecraft version

v1.19.40

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Expected to happen. There's a hotfix on its way that supports 1.19.40.
Closing for now. Create a new issue in case you have problems with the later version.
