### ISSUE TITLE
Doesn't work in 1.19.41 (Singleplayer and Aternos Server)

### ISSUE THREAD

**Issue by ciisarmz** [SIsilicon/WorldEdit-BE#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Hi! Yesterday I downloaded the mod for Bedrock for the first time, I did it with the standard version for singleplayer but it didn't work either in worlds already created or in new ones, despite having followed the steps in the documentation. I thought it was an exclusively singleplayer bug, so I tried on the external server but it didn't either.

**Although, reviewing the Aternos server log I discovered an error that I am attaching.**

**SINGLEPLAYER:**
![1](https://user-images.githubusercontent.com/72163544/204553230-f1ed9c74-8dcb-4908-ae30-3fad768ff2f6.PNG)
![22](https://user-images.git
![33](https://user-images.githubusercontent.com/72163544/204553260-226d11a1-f24d-4469-a5d5-c816e7444b3e.PNG)
hubusercontent.com/72163544/204553250-8a1940ec-63fc-4b6a-99a4-4c02c9733cc8.PNG)
![5](https://user-images.githubusercontent.com/72163544/204553435-068da033-abc5-49a9-b652-030374ff3d06.PNG)

**ATERNOS SERVER**

![server1](https://user-images.githubusercontent.com/72163544/204554005-71223118-a4e5-4c2e-9c60-414ee22e2999.PNG)

![server2](https://user-images.githubusercontent.com/72163544/204554020-5ec58227-97d9-43f9-adba-30875f4d940e.PNG)

![server3](https://user-images.githubusercontent.com/72163544/204554063-41395b84-dc78-4da7-91b0-2dadafecd98e.PNG)

### Expected behaviour

I expected the addon work fine :(

### Steps to reproduce

1. Install the mod by following the documentation steps and aternos addons installation steps.
2. Configure a new world or one already created with experiments.
3. Add "worldedit" tag
4. Try ";help" or ":kit" command
5. Cry :(

### Content logs

![server1](https://user-images.githubusercontent.com/72163544/204555476-24720b47-932f-4582-99ae-22300fa0abe8.PNG)

### Minecraft version

1.19.41

### Device and operating system

Windows 10 in a MacBook Pro 2013 15" (BootCamp)

### Additional info

1. Yes, i tried to reinstall minecraft
2. I tried download the mod again, twice
3. I tried to install the addon in aternos in all possible ways (also creating behavior_packs and resource_packs folders inside "world")
4. Sorry if my English is wrong, I'm a Spanish speaker.
5. Congrats to the whole team, they do a wonderful job!

**Comment by SIsilicon** [comment]
@ciisarmz what version of the addon are you using?

**Comment by ciisarmz** [comment]
Hi! I had this problem when downloading version 1.19.40 for my minecraft in 1.19.41; I downloaded it from MCPEDL but now I'll try WEdit 1.19.41 to see if that's the problem, give me a few minutes.

**Comment by ciisarmz** [comment]
It works now! What happens is that the only download link that was in MCPEDL was 1.19.40 and I assumed that it was the most recent version, also I did not think that this version would not be compatible with the version of my Minecraft 1.19.41 for 0.0.01 haha, thank you all! I will enjoy the mod that I wanted to install so much.
