### ISSUE TITLE
//chunk command

### ISSUE THREAD

**Issue by SIsilicon** [SIsilicon/WorldEdit-BE#131]
This command makes you select your current, or specified chunk.

Permission: `worldedit.selection.chunk`
Usage: `;chunk [-cs] [coordinates]`
[coordinates]: The chunk to select
[-s]: Expand your selection to encompass all chunks that are part of it
[-c]: Use chunk coordinates instead of block coordinates

**Comment by CrackedMatter** [comment]
Implemented by #146
