### ISSUE TITLE
Addon replies sounds like variables

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [SIsilicon/WorldEdit-BE#14]
**Describe the bug**
Addon replies sounds like variables, I don't know if this is a bug or not but shouldn't they be proper messages instead?

**To Reproduce**
1. Just do any command involving WE

**Expected behavior**
An proper message instead of generic variable like naming replies?

**Screenshots**
![Screenshot_20211107-011248_Minecraft](https://user-images.githubusercontent.com/30568955/140619712-d60beb03-c336-41ca-af18-74ec703fa0c0.jpg)

**Content Logs (if applicable):**
Paste content logs from Minecraft here.

**Minecraft Version:**
1.17.41 (Android)

**Additional context**
-

**Comment by SIsilicon** [comment]
Did you add the addon's resource pack to the world?
If so, what's your game's current language?

**Comment by RealEthanPlayzDev** [comment]
> Did you add the addon's resource pack to the world? If so, what's your game's current language?
Oh, the "RE" version was a resource pack? I didn't knew that, for language it's set to English US
