### ISSUE TITLE
Cant break blocks when using stacker tool

### ISSUE THREAD

**Issue by ItsMatthijs** [SIsilicon/WorldEdit-BE#147]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

![Screenshot_20221228_143532_Minecraft](https://user-images.githubusercontent.com/121669251/210061003-5fecee75-3f22-4f9c-8017-4b133d5ceccb.jpg)

### Expected behaviour

> 

### Minecraft version

1.19.51

### Device and operating system

Android 13

**Comment by SIsilicon** [comment]
Inferior version of https://github.com/SIsilicon/WorldEdit-BE/issues/148

@ItsMatthijs Next time, you can just edit your bug report instead.
