### ISSUE TITLE
Toggleable Debug messages

### ISSUE THREAD

**Issue by Ultr4Anubis** [SIsilicon/WorldEdit-BE#15]
Allow the Debug messages when the world is loaded up or when a player joins to be toggleable

This would be extremely helpful to those who are using the addon on a server otherwise it clogs up chat with debug messages.

**Comment by SIsilicon** [comment]
There's a file called `config.js` in the `scripts` folder of the addon. There you can set DEBUG to either true or false. The addon is still WIP so I didn't document it yet.

**Comment by SIsilicon** [comment]
By the way, were DEBUG messages showing for you? The addon was exported with DEBUG disabled last I checked.

**Comment by Ultr4Anubis** [comment]
They were showing on load up. Just looked at the config.json and it was set to true.

**Comment by SIsilicon** [comment]
Strange... Ok, setting it to false should fix your problem.

**Comment by SIsilicon** [comment]
Just checked the latest release has DEBUG disabled. Did you download the main source?

**Comment by SIsilicon** [comment]
This is now documented in the docs page.
