### ISSUE TITLE
The mod is running abnormally on the server

### ISSUE THREAD

**Issue by Kreswanan** [SIsilicon/WorldEdit-BE#151]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

Added to the server, it can be used normally at the beginning, but it will start to report an error after using it too many times, prompting **TypeError: cannot read property 'empty' of null**, you must restart the server or enter reload in bds to return to normal. But after a while, it will start reporting errors again. Everyone on the server has this problem.

### Expected behaviour

The mod runs normally on the server.

### Steps to reproduce

1.Enter the server and use worldedit, it can be used normally
2.The number of uses gradually increased, and errors began to be reported when filling the selection area, and sometimes the wooden ax selection area could not be used normally
3.Restart the server, or enter **reload** in bds, it can return to normal.
4.After a while, it will start reporting errors again.

### Content logs

```
[Scripting][warning]-starting

[Scripting][warning]-[LOG] [07:39:49 PM] Time taken to execute: 252ms (0.252 secs)

[Scripting][warning]-[LOG] [07:39:49 PM] Processing command ';set air' for 'ChristianBez787'

[Scripting][warning]-starting

[Scripting][warning]-[LOG] [07:39:49 PM] Time taken to execute: 262ms (0.262 secs)

... ...

[Scripting][warning]-[LOG] [07:40:22 PM] Processing command ';set air' for 'ChristianBez787'

[Scripting][warning]-[WARN] [07:40:22 PM] A ticking area could not be created for job # 96

[Scripting][warning]-starting

[Scripting][warning]-UnloadedChunksError: worldedit.error.saveHistory true hello

[Scripting][error]-[ERROR] [07:40:23 PM] Command ';set air' failed for 'ChristianBez787' with msg: {"rawtext":[{"text":"UnloadedChunksError: "},{"translate":"worldedit.error.saveHistory","with":[]}],"lastElementIdx":1}

[Scripting][warning]-[LOG] [07:40:30 PM] Processing command ';pos1 -19933 63 19890' for 'ChristianBez787'

[Scripting][warning]-[LOG] [07:40:30 PM] Time taken to execute: 0ms (0 secs)

[Scripting][warning]-[LOG] [07:40:32 PM] Processing command ';pos2 -19924 63 19885' for 'ChristianBez787'

[Scripting][warning]-[LOG] [07:40:32 PM] Time taken to execute: 0ms (0 secs)
```
### Minecraft version

1.19.51

### Device and operating system

Windows Server 2022 21H2/Bedrock Dedicated Server(BDS)

### Additional info

![2023-01-08 (1)](https://user-images.githubusercontent.com/101116355/211215742-a221b2ee-0f39-467e-94e3-59a7e0cbbd7b.png)
![2023-01-08](https://user-images.githubusercontent.com/101116355/211215754-ae7f4e12-9d92-4190-ad4a-feb4a78c6f72.png)

**Comment by SIsilicon** [comment]
Hmm. Could you do `/tickingarea list`? I have a feeling there could be a leak

**Comment by Kreswanan** [comment]
There are many "weditjob" tickingarea. These are not added by me.
![Uploading Screenshot_2023-01-09-07-23-26-72_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

**Comment by Kreswanan** [comment]
![QQ图片20230109072904](https://user-images.githubusercontent.com/101116355/211224380-337e1272-c21a-44a4-8ba9-cb3e158921f3.jpg)
There are many "editjobs" tickingarea, these are not added by me.

**Comment by Kreswanan** [comment]
![image](https://user-images.githubusercontent.com/101116355/211224569-220b1c68-fdb7-42a6-bb78-84ca4767e2ac.png)
There are many "weditjobs" tickingarea, these are not added by me.

**Comment by SIsilicon** [comment]
I knew it. The ticking areas are not being deleted properly.
I'll get a bugfix cooked up, but in the meantime, deleting those tickingareas should do the trick.
You'll have to do it periodically though

**Comment by Kreswanan** [comment]
That would be great, thank you

**Comment by SIsilicon** [comment]
Actually, it looks like their might be another bug happening here. I'll keep investigating

**Comment by SIsilicon** [comment]
This should be fixed in the latest pull request (https://github.com/SIsilicon/WorldEdit-BE/pull/153). Can you try it out for me and let me know if it works @Kreswanan?
[WorldEdit.server.zip](https://github.com/SIsilicon/WorldEdit-BE/files/10395214/WorldEdit.server.zip)

**Comment by Kreswanan** [comment]
Is it download this zip file? It still looks like the error will occur.
![Uploading -296f665bc9afc6d2.jpg…]()

**Comment by Kreswanan** [comment]
![QQ图片20230112114113](https://user-images.githubusercontent.com/101116355/211970586-ce4ec144-7e49-4940-93e7-be58e0d69d74.jpg)
Is it download this zip file? It still looks like the error will occur.

**Comment by Kreswanan** [comment]
Meanwhile, the fill block picker can pick other blocks, except air. The area can be filled normally, but the selection particles cannot be displayed.

**Comment by Kreswanan** [comment]
Still need to enter "reload" in the BDS console to return to normal.

**Comment by Kreswanan** [comment]
Unfortunately, it didn't work.

**Comment by SIsilicon** [comment]
Same errors?

**Comment by Kreswanan** [comment]
It seems that the problem of error reporting no longer occurs, but there are some other problems.  For example, after the server has been running for a period of time, air cannot be selected as the filling block. At the same time, we can make normal selections but the selection particles cannot be displayed. I'm not sure if this is an issue with the server itself or with the mod.

**Comment by SIsilicon** [comment]
Ok, since these are two separate problems, I ask that you make a bug report for each of them. Seeing that one bug has been fixed though, I'll merge the changes and close this issue.
