### ISSUE TITLE
Custom tool for custom command

### ISSUE THREAD

**Issue by Jim-no-surname-provided** [SIsilicon/WorldEdit-BE#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

For a pc player it is really easy to use the commands, but for a phone, or console player it isn't as smooth, since there's no easy way to type nor autosuggest like with the normal commands.

Also, I use ;move, ;stack and ;expand quite a lot, and it would be nice to be able to get a tool that does exactly that, so I don't need to type them always again.

### Proposed Solution

I therefore propose a new section on the "Adjustments > Tools > Create new tool" called for example "Custom command" where you can type a command like ";sel" or ";expand 1" and then an object of your choice gets binded to that specific command.

### Alternatives

You could have for example a text area on the settings menu to type the command, if that is possible.

Alternatively, if that's not possible, it could get binded to the **last command** you used on the chat.

If you make it so that it types textually what you wrote onto the chat, it could also be used to execute vanilla commands, like "/kill @e[type=item]"

**Comment by SIsilicon** [comment]
Added
