### ISSUE TITLE
MC Bedrock issue?

### ISSUE THREAD

**Issue by AAEexecutive** [SIsilicon/WorldEdit-BE#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

This might be me doing something wrong or my computer not handling WE, but while Bedrock Edition says that both the resource pack and the behavior pack are enabled (Screenshots 1 and 2), and both Holiday Creator features and Beta APIs are enabled (screenshot 3) the game isn't recognizing any plugin commands. I have tried, per the advice of a handful of tutorials, to first type "/tag @s add builder" and it says that I successfully added the tag (Screenshot 4), but when I type ";help" it tells me that I don't have permission to use that command (Screenshot 5).
![Screenshot 1](https://user-images.githubusercontent.com/125088147/218188333-9218d142-282c-473b-9823-593444143ace.png)
![Screenshot 2](https://user-images.githubusercontent.com/125088147/218188357-cab81d71-9c5c-41df-ac21-f553313aa99f.png)
![Screenshot 3](https://user-images.githubusercontent.com/125088147/218188374-935d04b0-6d2c-4f9d-9c0c-764c356316ae.png)
![Screenshot 4](https://user-images.githubusercontent.com/125088147/218188389-af1519b4-378f-4a73-8668-96d06dd23f0b.png)
![Screenshot 5](https://user-images.githubusercontent.com/125088147/218188407-9119dbcf-da1f-451e-a407-15f05d7702bd.png)

### Expected behaviour

The tutorials say that if I give myself the tag 'builder', then I should be able to access all the World Edit commands such as /pos1, /pos2, /copy, /paste, and /fill.

### Minecraft version

1.19.3

### Device and operating system

Windows 10

**Comment by SIsilicon** [comment]
You must tag yourself with `worldedit`; not `builder`.
If you have any more problems with installation, see this bug report. https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Comment by AAEexecutive** [comment]
Thank you so much!

AAEexecutive
