### ISSUE TITLE
Commands not processed in multiplayer

### ISSUE THREAD

**Issue by JaylyDev** [SIsilicon/WorldEdit-BE#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Any commands such as `;cut` or `;paste` do not work when **multiple players have the worldedit tag** are in the same world at the same time, this happens after everyone except the host in the world.

In content log the add-on says the command has been processed, but no results are returned.

### Expected behaviour

Commands should be processed when multiple players in world.

### Steps to reproduce

1. Apply the add-on (with experimental features required) to world
2. Let another player join the world
3. Give every player worldedit permission
4. Let a player run `;wand`, content log says command is processed but the player never got the axe (it's not processing for every command)

### Minecraft version

1.19.60

### Device and operating system

Windows 10

**Comment by SIsilicon** [comment]
Check if this still happens in 0.8.0

**Comment by JaylyDev** [comment]
I can confirm it's fixed. Thanks!
