### ISSUE TITLE
Not a bug, but help needed

### ISSUE THREAD

**Issue by AAEexecutive** [SIsilicon/WorldEdit-BE#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

This is (probably) my own issue and not the plugin's, but I am under 18 and can't use Discord. I am trying to build a mountain shaped like my bunk bed, but so far all I have is a set of giant rectangular prisms. I would like it to look more natural and random-ish. I have three major issues:
1 and 2 are sort of connected. I would like for my mountain to have sides that are steep, but realistic and not just a sheer wall of andesite. And with the andesite, I would like to paint a gradient of stones instead of it all being the same color. I was looking at the WorldEdit documentation page and the ;help 2 page as well as [this video](https://www.youtube.com/watch?v=rOMXNSEATr8&t=618s), which is for the Java plugin, but I thought it would be similar, but apparently it's not as close as I thought. With the video, I thought that if I made a sphere brush that was randomly filled with gravel or sand, then I could use it on the wall and it would fall into a random, natural-looking pattern.
3 is that when I add the "roof" (my top bunk), the light barely shines in through the sides. (I know this is a normal Minecraft mechanic and not a WorldEdit thing.) I was going to try and fill the space with light blocks, but they disappear when I scroll off of them to the Pattern Picker. Is there a command to set the pattern? 
Thank you for your time!

### Expected behaviour

I honestly have no idea how this will work. I've been watching YouTuber TrixyBlox building the Ultimate Survival World, and while I know it's sped up a lot, he doesn't seem to have any sort of technical trouble. I'm guessing somewhere there are commands to do what the person in the tutorial video did in Java, and to manually select the pattern to be used. Which reminds me! I tried to make a normal sphere brush with the WorldEdit Settings menu, but it didn't show anything in my hand that could be bound to a brush. Everything, including my unbound tools, disappeared temporarily and all that was there was the exit button in slot 9.

### Minecraft version

1.19.3

### Device and operating system

Windows 10

**Comment by SIsilicon** [comment]
I recommend updating Minecraft to the latest version so you can use the latest WorldEdit features

**Comment by AAEexecutive** [comment]
Where do I do that?

**Comment by AAEexecutive** [comment]
OK, the Microsoft Store says all my apps are up to date. What now?

**Comment by SIsilicon** [comment]
That's why I'm telling you to look it up.

**Comment by AAEexecutive** [comment]
Oh, sorry! 🤦‍♂️

Okay, Minecraft is updated to 1.19.3, which is the highest version displayed. 

The items seem to be showing up now and I can bind the brushes to them. So the ‘bug’ is fixed. Thank you!

Do you happen to know how to phrase the command to make a sphere brush, say, 60% air and 40% gravel?

**Comment by SIsilicon** [comment]
1.19.60 is the latest stable release of Minecraft Bedrock.
As for the brush, you can use the command `;br sphere 60%air,40%gravel "radius"`. The syntax is almost identical to Java edition.

**Comment by AAEexecutive** [comment]
Oh yes, I do see that I have 1.19.62. The brushes are still disappearing (and I’ve noticed that if I open a chest whilst choosing a wand, I can drag items from the chest and my extended inventory into my hotbar and I can bind them, but then they immediately vanish) but the gravel worked, so I will not be needing them urgently. The same video said that I should be able to cover a specific block with pixel art by copying it and typing “//replace 1 #copy”. I tried this, and typing it with a semicolon instead of a double backslash, but it isn’t working. Do you have any ideas?

Thanks!

**Comment by SIsilicon** [comment]
It's #clipboard. Not #copy. And 1 alone cannot be used as a replace mask.

**Comment by AAEexecutive** [comment]
Okay, what can I use?

**Comment by SIsilicon** [comment]
The block's actual ID. I see what block you're going for. It would be `;replace stone #clipboard`

**Comment by AAEexecutive** [comment]
Ah, OK!

It seems to have worked… sort of. On my mountain, it appears to have cut off the top of the pattern and moved it to the bottom. Do you have any idea what’s going on?

**Comment by SIsilicon** [comment]
Closing
