### ISSUE TITLE
No Enable GameTest Framework toggle

### ISSUE THREAD

**Issue by breezy708** [SIsilicon/WorldEdit-BE#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Ive installed the mcaddon and loaded it, but it isnt working and i have a feeling is because my version of mc doesnt have this toggle in the settings menu. running version 1.19.62

### Expected behaviour

Need to enable the gametest framework toggle

### Minecraft version

1.19.62

### Device and operating system

PC

**Comment by SIsilicon** [comment]
It's now called Beta API
