### ISSUE TITLE
Not rotated trapdoors and stairs

### ISSUE THREAD

**Issue by KeineAhnungwasichhiermache** [SIsilicon/WorldEdit-BE#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Trapdoors and stairs are not rotated or flipped at their opposite or maching direction like they used to be. This stopped working since the newest Update (1.19.70 Windows 10 Edition and Pocket Edition).
On the attached picture you can see on the left side how It should be and on the right side the flipped part of the building, that has the issue.

### Expected behaviour

When an area has been copied that contains stairs and trapdoors which I flip after selecting, trapdoors and stairs should face in the flipped direction. All other blocktypes still work perfectly fine.

### Steps to reproduce

1. Set up a testarea that contains specific placed stair and trapdoors.
2. select the area.
3. flip or rotate it in 90 degree directions or flip it for example left or right.

### Minecraft version

1.19.70

### Device and operating system

Windows 10 on a Asus Rog-series notebook

### Additional info

![Minecraft_Bedrock_screenshot](https://user-images.githubusercontent.com/116166860/226122191-d04239d5-591b-46c3-9950-96c1be08bdf1.jpg)

**Comment by SIsilicon** [comment]
Check if it works now in 1.19.80

**Comment by KeineAhnungwasichhiermache** [comment]
It works flawless since the newest version of the addon.
Thank you!

:]

Am 04.05.2023 um 04:02 schrieb Roujel Williams ***@***.***>:

﻿

Check if it works now in 1.19.80
