### ISSUE TITLE
no world edit, only this warning on the pack. no commands work for it , nothing 

### ISSUE THREAD

**Issue by CaffineZombie** [SIsilicon/WorldEdit-BE#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

ui/how_to_play_screen.json: Child controls must have unique names: 

section_content_panels/general_tips_sections/wedit:quick_start_section
section_content_panels/general_tips_sections/wedit:license_section
selector_stack_panel/how_to_play_selector_pane/padding_00
selector_stack_panel/how_to_play_selector_pane/worldedit_category
selector_stack_panel/how_to_play_selector_pane/wedit:quick_start_button
selector_stack_panel/how_to_play_selector_pane/wedit:license_button
selector_stack_panel/how_to_play_selector_pane/minecraft_category

In the future this will be an error and this file won't load.

### Expected behaviour

the worldedit feture to work, like even a little

### Steps to reproduce

download to realm. 

### Content logs

ui/how_to_play_screen.json: Child controls must have unique names: 

section_content_panels/general_tips_sections/wedit:quick_start_section
section_content_panels/general_tips_sections/wedit:license_section
selector_stack_panel/how_to_play_selector_pane/padding_00
selector_stack_panel/how_to_play_selector_pane/worldedit_category
selector_stack_panel/how_to_play_selector_pane/wedit:quick_start_button
selector_stack_panel/how_to_play_selector_pane/wedit:license_button
selector_stack_panel/how_to_play_selector_pane/minecraft_category

In the future this will be an error and this file won't load.

### Minecraft version

1.19.7 ish

### Device and operating system

winmdows 10 

### Additional info

this is the best addon out there, please please fix .

**Comment by SIsilicon** [comment]
Have you checked if it works on a local world? Also please provide the version number of the addon

**Comment by CaffineZombie** [comment]
Current version world edit on curse forge won't work in bedrock like it did
before. No commands or anything. Fresh download deleted all other copies.
Reinstalled them all. Nothing.
Do you need to update for the new game updates ? Bedrock.
