### ISSUE TITLE
Block Placement

### ISSUE THREAD

**Issue by headqutar** [SIsilicon/WorldEdit-BE#18]
I can't place colored blocks, idk if it happens for glass, wool, etc but for concrete, I can only place "concrete" which is white.

**Comment by SIsilicon** [comment]
Ah, you see, it's how Minecraft treats blocks of different variations. To the game, red concrete, white concrete, any colour of concrete are the same block. They just have different states. The same thing happens if you use the `/setblock` command.

**Comment by SIsilicon** [comment]
To change which variation of a block you are using, you have two options.
1. Give a data value - eg: wool:0 is white wool (default), and wool:5 is lime wool.
2. Give block states - eg: wool['color':'yellow'] is yellow wool

**Comment by headqutar** [comment]
Ok, thank you!

**Comment by SIsilicon** [comment]
This is now documented in the docs page.
