### ISSUE TITLE
Не работает мод на версии 1.19.80 

### ISSUE THREAD

**Issue by Maksimkanenegr** [SIsilicon/WorldEdit-BE#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Я на своем устройстве Redmi note 7 решил скачать себе мод WorldEdit на Майнкрафт пе версии 1.19.80. я включил все нужные функции, создание праздников и бета айпи но при в воде верной команды /tag @s add worldedit у меня мод не работал. Я переустанавливать Майнкрафт, переустанавливать мод(я проверил, что это был мод самой новой версии) но все равно при входе в мир у меня не работает мод, я подключал этот мод единственным в пакете текстур и единственным в наборе параметров и ничего не вышло

### Expected behaviour

Я хотел чтобы этот мод сработал

### Steps to reproduce

Я не знаю что писать, переводчик неправильно перевел

### Content logs

![Screenshot_2023-05-30-23-56-58-358_com mojang minecraftpe](https://github.com/SIsilicon/WorldEdit-BE/assets/135068761/80cce602-1212-4fc6-9874-53c40ecea44f)

### Minecraft version

1.19.80

### Device and operating system

Redmi note 7

### Additional info

Нету

**Comment by SIsilicon** [comment]
Where did you download the addon from?

**Comment by Maksimkanenegr** [comment]
> Откуда вы скачали аддон?
https://mcpehub.org/mods/7102-worldedit-be.html

**Comment by SIsilicon** [comment]
> > Откуда вы скачали аддон?
> > https://mcpehub.org/mods/7102-worldedit-be.html

I have not made my addon officially available there. Please download it from MCPEDL, CurseForge or here in GitHub.
https://github.com/SIsilicon/WorldEdit-BE/releases/tag/v0.8.0
