### ISSUE TITLE
Yellow! Missing dependency On the add on making it not work in game.  1.19.83

### ISSUE THREAD

**Issue by S3an03** [SIsilicon/WorldEdit-BE#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I was using the add on for about 2 weeks but yesterday I noticed that it just stopped working. I’ve deleted the add on multiple times and reinstalled it also I’ve deleted Minecraft, the add on gets successfully imported but always has the yellow! next to it.

### Expected behaviour

I thought would work after I uninstalled and reinstalled 

### Steps to reproduce

![IMG_0064](https://github.com/SIsilicon/WorldEdit-BE/assets/135070145/ea2c9a20-3af5-4330-90ae-5e2af0e4e5c7)

![IMG_0065](https://github.com/SIsilicon/WorldEdit-BE/assets/135070145/0c493027-6f75-44ad-a27e-f9d3488f2257)
![IMG_0066](https://github.com/SIsilicon/WorldEdit-BE/assets/135070145/1a74c59d-c650-4da6-a31b-7e130dab2f7c)
![IMG_0068](https://github.com/SIsilicon/WorldEdit-BE/assets/135070145/2dae42e8-c937-4026-9492-0d0d25127b7e)

### Content logs

None

### Minecraft version

1.19.83

### Device and operating system

iPad Pro (12.9-inch) (5th generation)

**Comment by SIsilicon** [comment]
Those warning don't affect the addon's performance. What matters is when they're applied in your world.
