### ISSUE TITLE
Broken after 1.20

### ISSUE THREAD

**Issue by tacobellcry** [SIsilicon/WorldEdit-BE#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

No longer works after 1.20, after re-downloading and re-applying to world.

### Expected behaviour

Works on world.

### Steps to reproduce

1. Download addon
2. Apply to world
3. Give WorldEdit permissions to self
4. Try to use wooden axe on block, right click with and without crouching
5. Nothing happens

### Minecraft version

1.20

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
0.8 will come soon with 1.20 support
