### ISSUE TITLE
needed tag bug (language bug)

### ISSUE THREAD

**Issue by vytao-do-miau-miau** [SIsilicon/WorldEdit-BE#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

in some specific languages, for example: portuguese from brazil, when you go to **how to play** > **quick start**, it says the tag you need to use the commands is "builder", but it's actually "worldedit"

### Expected behaviour

even tho the language changes, it is supposed to say the tag you need is "worldedit"

### Steps to reproduce

1 - change the language to portuguese (brazil)
2 - go to your world
3 - go to the menu
4 - go to "como jogar" (how to play)
5 - go to "início rápido" (quick start)
6 - on the right side, you can see that i shows the wrong tag that you need

### Minecraft version

1.20.0

### Device and operating system

windows 10

### Additional info

hell

**Comment by SIsilicon** [comment]
Should be fixed now
