### ISSUE TITLE
The "how to play" help page dosent.

### ISSUE THREAD

**Issue by LAANHEL** [SIsilicon/WorldEdit-BE#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Content Logs (if applicable):**
Paste content logs from Minecraft here.

**Minecraft Version:**
[e.g. 1.17.41]

**Additional context**

**Comment by SIsilicon** [comment]
Please fill in the issue template where needed. I can't just work with "help page is not helpful". I'll open this issue again once you do.
