### ISSUE TITLE
Tidak berfungsi saat menjalankan/tag @s add worldedit

### ISSUE THREAD

**Issue by Hai099** [SIsilicon/WorldEdit-BE#192]
[]([]([###](https://drive.google.com/file/d/129HbpY-RcdCDuE3p-YX01mLewE15vK0Y/view?usp=drivesdk))) Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I can't run the command/not given permission, even though I did the command /tag @s add worldedit. And I tried other commands like ;wand ;navwand ;kit

And here is the video link I mean from this issue (https://drive.google.com/file/d/129HbpY-RcdCDuE3p-YX01mLewE15vK0Y/view?usp=drivesdk)

### Expected behaviour

Please help to solve this.

### Minecraft version

1.20.10.25

### Device and operating system

Android 10/Miui 12

**Comment by SIsilicon** [comment]
0.8.0 does not support Minecraft 1.20.10. Wait for a minor update to the addon

**Comment by Hai099** [comment]
Thank you for the help.
