### ISSUE TITLE
Wand doesn't give anything in a multiplayer game

### ISSUE THREAD

**Issue by ltroublve** [SIsilicon/WorldEdit-BE#2]
using ;wand command doesn't do anything, i havent tried it in single player yet. i used the /tag @s add builder command aswell

**Comment by BLAZERRAJ** [comment]
I have some questions

1. How to install this add-on on alternos server
2. I cant get wand even doing everything in mcpe on Android
3. Plz help me

**Comment by SIsilicon** [comment]
@ltroublve, @BLAZERRAJ 
Here's what I found out when using aternos.
1. You need to import, or create a world to edit experimental features.
2. Aternos doesn't import js files with world exports, so half the addon doesn't work when imported with a world.

So here's the solution I found.
First, you must either create a new world from aternos, or import an exported mcworld with experimental features enabled. The addon must **not** be included with this world.
Then, you must import the addon to aternos separately. When you enter the world with op, the add-on will work.

**Comment by BLAZERRAJ** [comment]
I have also tried this in single player world the command does not give me wand plz help .
I think it only work for win10 edition

**Comment by BLAZERRAJ** [comment]
I have get another world edit but I need your ,your wand is best but by the time I am using this
[WorldEdit Addon (CenterUI).mcaddon.zip](https://github.com/SIsilicon/WorldEdit-BE/files/7361682/WorldEdit.Addon.CenterUI.mcaddon.zip)

**Comment by SIsilicon** [comment]
The one on play store and from the internet are likely the same. If I were to give you a copy, the game would still know you haven't bought it. Is the version of Minecraft you have 1.17.30 or above?

**Comment by SIsilicon** [comment]
You think you can record the process of installing the addon to a new world, so that I could probably see what went wrong?
This is strange 'cause the addon is working for other people too.

**Comment by SIsilicon** [comment]
I'm not sure what's wrong here. 
My second comment in this issue asked to have creator log files and GUI enabled. Hopefully some error message shows up when you try installing the addon again. Then Minecraft could tell me what's going on. If this doesn't show any useful info, I'm not sure what else to do.

**Comment by SIsilicon** [comment]
@BLAZERRAJ I can't remember, did you have a space in your player name?

**Comment by PookieWasTaken** [comment]
Same here. I'm still suffering with the same problem but mine says "You don't have permission to execute command" when I use any command with ";" even though I did the "/tag @s add builder".

**Comment by SIsilicon** [comment]
@PookieWasTaken What's your IGN (Player name)?

**Comment by PookieWasTaken** [comment]
> @PookieWasTaken What's your IGN (Player name)?

Sorry for the late reply. It's "PookieBanana26". It didn't have spaces in it because it is a xbox account.

**Comment by SIsilicon** [comment]
Could you make a short video of yourself installing the addon to a new world and using it? That way I could probably see what's happening. Also enable content log as stated in the README bug report section while recording.

**Comment by PookieWasTaken** [comment]
Sorry for taking so long but here's the [link](https://youtu.be/WKBWHZnbvpI) for the video. I don't think that this may help you but good luck!

**Comment by SIsilicon** [comment]
What version of the addon were you using?

**Comment by PookieWasTaken** [comment]
I was using the v.0.1.2 version last time and had the same problem but in the video I was using v.0.1.3 version.

**Comment by SIsilicon** [comment]
Here try this. It's the latest development version.
[WorldEdit.mcaddon.zip](https://github.com/SIsilicon/WorldEdit-BE/files/7456852/WorldEdit.mcaddon.zip)
If you are still having problems, if you have discord we could talk further there tomorrow.

**Comment by PookieWasTaken** [comment]
Okay, I'll test it later. Thanks!

**Comment by PookieWasTaken** [comment]
> Here try this. It's the latest development version. [WorldEdit.mcaddon.zip](https://github.com/SIsilicon/WorldEdit-BE/files/7456852/WorldEdit.mcaddon.zip) If you are still having problems, if you have discord we could talk further there tomorrow.

Okay so I tested the file that you sent and it has the same problem like earlier. The commands and items still don't work even with the tag. If you'd like we can just continue this on discord if that's alright?

**Comment by SIsilicon** [comment]
Yeah, send me your Discord.

**Comment by BLAZERRAJ** [comment]
> @BLAZERRAJ I can't remember, did you have a space in your player name? If so, 0.1.3 should now have that issue fixed.

Ok but please link

**Comment by PookieWasTaken** [comment]
> Yeah, send me your Discord. We can discuss this tomorrow though. It's very late where I am.

It's PookieBanana#4528 just send me a message if you're online.

**Comment by PookieWasTaken** [comment]
> Ok but please link

Here's the [link](https://mcpedl.com/worldedit-be-addon/) if you still want it though.

**Comment by SIsilicon** [comment]
@PookieWasTaken I'm online now.

**Comment by PookieWasTaken** [comment]
@SIsilicon same here

**Comment by SIsilicon** [comment]
Closing due to lack of support.
