### ISSUE TITLE
in 1.20.12 the addon does not work, no command

### ISSUE THREAD

**Issue by DjSneijder** [SIsilicon/WorldEdit-BE#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I put a command and it does nothing, I give myself the permissions and it continues the same

### Expected behaviour

that will work

### Minecraft version

1.20.12

### Device and operating system

windows 10

**Comment by thecrazy** [comment]
I had the same problem until I enabled the behavior pack in the map settings

**Comment by SIsilicon** [comment]
As this is just an installation problem, marking as a duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/134
