### ISSUE TITLE
Doesn’t work in current version

### ISSUE THREAD

**Issue by FurfiWolf** [SIsilicon/WorldEdit-BE#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Nothing works and nothing happens

### Expected behaviour

Supposed to work

### Steps to reproduce

Load it in current version of Minecraft and try using it

### Minecraft version

1.20.31

### Device and operating system

iOS

**Comment by SIsilicon** [comment]
The latest version of WorldEdit 0.8.2 works on 1.20.30 and its hotfixes
