### ISSUE TITLE
Update to support version 1.20.01

### ISSUE THREAD

**Issue by GsThePro** [SIsilicon/WorldEdit-BE#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

Update to support version 1.20.01

### Proposed Solution

Update 

### Alternatives

Update 

### Additional info

Update

**Comment by CrackedMatter** [comment]
Download [v0.8.0](https://github.com/SIsilicon/WorldEdit-BE/releases/tag/v0.8.0)
