### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by ForbiddenGoose1234** [SIsilicon/WorldEdit-BE#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The world edit is loaded into my world, but new errors are showing up and it is as if nothing is downloaded. There are no items, instructions ect.

### Expected behaviour

I expect that I can no longer use this addon due to some form of bug or update, but I hope that something is done to fix this soon.

### Minecraft version

1.20.5

### Device and operating system

iOS

**Comment by SIsilicon** [comment]
What's your WorldEdit version?

**Comment by SIsilicon** [comment]
Closing this in favour of https://github.com/SIsilicon/WorldEdit-BE/issues/134
If you're still having issues, chat there
