### ISSUE TITLE
Redstone components don't rotate when you rotate a selection

### ISSUE THREAD

**Issue by Aspvpboss** [SIsilicon/WorldEdit-BE#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When you rotate a selection with redstone components in it. The redstone components keep the orientation they had before rotating.

### Expected behaviour

The redstone components should rotate however much you rotate.

### Minecraft version

1.20.51

### Device and operating system

Windows 11

### Additional info

![image](https://github.com/SIsilicon/WorldEdit-BE/assets/154620386/1180316b-6d83-4411-91d1-5fca4582dc05)

**Comment by SIsilicon** [comment]
Fixed as of the latest version
