### ISSUE TITLE
My resource pack has 2 errors

### ISSUE THREAD

**Issue by Galaxy214** [SIsilicon/WorldEdit-BE#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Error:
ui/how_to_play_screen.json: Can't find the control: section_content_panels/general_tips_sections

Error:
ui/how_to_play_screen.json: Can't find the control: selector_stack_panel/how_to_play_selector_pane

### Expected behaviour

I was expecting the tag to work but the pack won’t even activate due to the errors

### Minecraft version

1.20.51

### Device and operating system

Iphone 11

**Comment by SIsilicon** [comment]
Those errors are not important. What addon version did you install, and did you enable the beta api experimental feature?

**Comment by SIsilicon** [comment]
Closing this in favour of https://github.com/SIsilicon/WorldEdit-BE/issues/134
If you're having problems, chat there
