### ISSUE TITLE
[BUG] No permissions

### ISSUE THREAD

**Issue by neexz** [SIsilicon/WorldEdit-BE#23]
**Description** 
i turn on the addon and i dont have permissions

**Steps to reproduce** 

i type in /tag @p add builder
/give @p wand
and i select the object
and i dont have permission" you dont have permission to use this command"
pls help

**Expected behavior** 

**Minecraft version** 
1.17.41

**Device and operating system**
windows 10 | amd ryzen 1600af | gtx 1160s | 16gb ram 3200mhz

**Comment by SIsilicon** [comment]
Did you enable the Gametest framework?

**Comment by SIsilicon** [comment]
Did you mean `/give @p wedit:selection_wand`?

**Comment by SIsilicon** [comment]
@neexz Try this out. I think I found a fix for it.
[WorldEdit.mcaddon.zip](https://github.com/SIsilicon/WorldEdit-BE/files/7613743/WorldEdit.mcaddon.zip)

**Comment by neexz** [comment]
it dont work still :/

**Comment by SIsilicon** [comment]
The addon I gave you has debugging enabled. From the moment you join the world with the builder tag, what messages did you see?

**Comment by SIsilicon** [comment]
After which, type `/tag @s list` to see if you have the builder tag.

**Comment by neexz** [comment]
it works but how to select postion no 2?

**Comment by SIsilicon** [comment]
To mark your second selection, you need to tap on a block without shifting. I suggest you look into  `Settings > How to Play` for a tutorial on how to use the addon. Scroll all the way down for the quick start.

**Comment by SIsilicon** [comment]
Seeing as how this is now fixed, I'll close this. If you have any other issues, go ahead and report it in a new issue. :)
