### ISSUE TITLE
Not working for 1.20.0

### ISSUE THREAD

**Issue by DaKingOfMonkes** [SIsilicon/WorldEdit-BE#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Not working at all, any commands do not work.

### Expected behaviour

Should be working normally.

### Steps to reproduce

Give yourself the "worldedit" tag.

### Content logs

[Scripting][error]-Plugin [WorldEdit Bedrock Edition 0.8.5] - module [WorldEdit Bedrock Edition 0.8.5 - 1.0.0] requesting invalid module version [@minecraft/server-ui - 1.2.0-beta].
Available versions:
@minecraft/server-ui - 0.1.0
@minecraft/server-ui - 1.0.0
@minecraft/server-ui - 1.1.0-beta

[Scripting][error]-Plugin [WorldEdit Bedrock Edition 0.8.5] - module [WorldEdit Bedrock Edition 0.8.5 - 1.0.0] requesting invalid module version [@minecraft/server - 1.9.0-beta].
Available versions:
@minecraft/server - 0.1.0
@minecraft/server - 1.0.0
@minecraft/server - 1.1.0
@minecraft/server - 1.2.0
@minecraft/server - 1.3.0-beta

### Minecraft version

1.20.0

### Device and operating system

Android

### Additional info

I am using the 0.8.0 version of the addon found in the release tab, which according to the description, is compatible with the 1.20.0 version of Minecraft.

Behavior pack has error: Missing dependency with ID 'e304a4eb-f0a0-4979-ac17-7b0f46a555c8' and version '0.8.0'.

**Comment by SIsilicon** [comment]
0.8.5 doesn't support Minecraft 1.20.0

**Comment by SIsilicon** [comment]
Use this https://github.com/SIsilicon/WorldEdit-BE/releases/tag/v0.8.0
