### ISSUE TITLE
Brushes Stop Scripts in 0.9.0.3

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Using a brush tool in World Edit ceases all functionality and arrests all world edit scripts without generation.

### Expected behaviour

The desired brush tool etc to execute based on what you have entered and properly generate blocks without world edit’s scripts stopping from running.

### Steps to reproduce

Create a new brush (for example, try a sphere of sand without a mask) Once the brush is done, try it out. You’ll quickly notice that the particles dissapear, the tool doesn't generate the desired stuff, worldedit’s scripts will stop running and the world must be restarted. Restarting the world results in the same issue too

### Content logs

Unfortunately nothing was sent here for some odd reason.

### Minecraft version

1.20.80.20

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Should now be fixed by this commit https://github.com/SIsilicon/WorldEdit-BE/commit/0188e7a3ad8208dec562821daa6f7086b011526f
