### ISSUE TITLE
Wand with fill & pattern picker don’t work correctly.

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Filling an area fills it with incorrect blocks.

### Expected behaviour

Filling an area with blocks using the wand and fill tool w/ pattern picker should fill using desired settings.

### Steps to reproduce

Set a position and second position using the wand.
Then, use the pattern picker on-for example ‘diorite slab’ then use the fill tool to fill the area with that block and it will fill it to ‘end brick slabs’
This also happens with filling an area with green concrete, it doesn’t do anything or fills it with grass.

### Content logs

Unfortunately none

### Minecraft version

1.20.80.25

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Fixed in https://github.com/SIsilicon/WorldEdit-BE/commit/f826c113b07c2608aefb6f14a7647e3f6d73e49b. You should see the change in the next beta

**Comment by Hortseen** [comment]
Thank you so much for your dedication!! You are incredible🤍
