### ISSUE TITLE
Incompatible for 1.20.80.21 (0.9.0.3)

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Nothing works in the addon

### Expected behaviour

World edit works as expected

### Steps to reproduce

Try ‘;kit’ and no scripts load

### Minecraft version

1.20.80.21

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
What's the addon version? It's not expected of WorldEdit 0.8.5 to work with the 1.20.80 betas

**Comment by Hortseen** [comment]
0.9.0.3

**Comment by SIsilicon** [comment]
Yeah that will happen API changes frequently. It's expected so closing this. Wait until the next WorldEdit beta is out.
