### ISSUE TITLE
Flora Painting?

### ISSUE THREAD

**Issue by jami3rez** [SIsilicon/WorldEdit-BE#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

There seems to be no way to paint flora to a surface in the world? Looking at Worldedit in Java this was accomplished with a brush but just gives an error here. Am I just doing it wrong or is this a bug?

### Expected behaviour

I would expect to be able to set flora to a brush in the same way I can a block.

### Minecraft version

1.20

### Device and operating system

Windows 10

### Additional info

Worldedit 0.85

**Comment by SIsilicon** [comment]
You can just make an overlay brush That makes mostly air and _some_ flowers. Hold an item and run this command `;br overlay 95%air,5%*red_flower 3 -1 air` Where 3 is the brush radius.
