### ISSUE TITLE
;help [command:Command] doesn't work!

### ISSUE THREAD

**Issue by MelidoxCool** [SIsilicon/WorldEdit-BE#24]
I type _;help set_ or _;help cyl_ it doesn't show the info it needs to it just says "Showing page NaN of 6". There are also no examples that I can see. Also when I pick a spot and do _;set wool["color":"green"]_ it shows an error and if I put a space between the l in wool and [ it only makes the selected area white wool.

Hope this message doesn't come off too Karen sounding.

**Comment by SIsilicon** [comment]
In the case of the set command, you can't have spaces in the pattern definition, and you must use single quotes (') not double (").

**Comment by SIsilicon** [comment]
I'm not sure why `;help set` doesn't work though. Does `;help 3` work?

**Comment by SIsilicon** [comment]
Closed due to lack of info.
