### ISSUE TITLE
Not working on 1.20.71

### ISSUE THREAD

**Issue by Fenom-998** [SIsilicon/WorldEdit-BE#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

After the update all functions of the addon stopped working. i was using 0.8.5

### Expected behaviour

the addon have a yellow alert now

### Minecraft version

1.20.71

### Device and operating system

IOS

**Comment by snarkDADMin** [comment]
Also facing this issue on my daughter's iPad. 1.20.70 worked great, 1.20.71 was supposedly just a fairly small bugfix release according to the app store update notes, but it's busted WorldEdit PE, unfortunately.

**Comment by SIsilicon** [comment]
@Fenom-998 update to 0.8.6 @snarkDADMin I recommend you do the same
