### ISSUE TITLE
0.9.0.3 Incompatible with 1.20.80.23

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Nothing works

### Expected behaviour

Everything works as expected

### Steps to reproduce

Try to use world edit

### Minecraft version

1.20.80.22

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Yeah that will happen API changes frequently. It's expected so closing this. Wait until the next WorldEdit beta is out.

**Comment by Hortseen** [comment]
I hope this doesn't bother you but is there a timeframe when it could be available? Currently using it for touchups on a massive-scale project and wanna potentially know whether to prioritize other stuff first before this🤍 hugely appreciated your undying efforts on this mod🤍
