### ISSUE TITLE
Don’t lock addon loading to a specific version number

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

No matter what changes, even in a 0.00.00.01 update, the addon will break. This makes maintain ability really hard to stay ontop of and is really annoying. Let the addon work till the changes Mojang makes end up breaking it instead of just the version being a mismatch. This would help the addon flourish much more and would require less work just to patch it every Wednesday/Thursday forever just to allow it to load.

### Proposed Solution

Make the addon’s loading system be greater than or equal to the supported version number.

### Alternatives

Show us how to do it if you’re busy and can’t keep up with everything update mojang pushes

**Comment by SIsilicon** [comment]
>  Let the addon work till the changes Mojang makes end up breaking it instead of just the version being a mismatch.

That's the thing. They're _constantly_ breaking it. The addon uses the Beta APIs experiment which changes with every minor update. So every minor update, I have to update it. Sometimes it's not a version change either. Parts of the API change that I have to update too.

**Comment by Hortseen** [comment]
Awwww, I didn't think just a couple lines in the patch notes could do so much damage

**Comment by hongqiang666** [comment]
1.20.72.1 can not use

**Comment by SIsilicon** [comment]
> 1.20.72.1 can not use

WorldEdit 0.8.6 works with that version. I downloaded from CurseForge if that helps

**Comment by hongqiang666** [comment]
Thank you very much
