### ISSUE TITLE
;replace stairs makes stairs always face east.

### ISSUE THREAD

**Issue by brotai** [SIsilicon/WorldEdit-BE#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Every time you try to change the type of stairs on your build, they all face east. [FIXED]

### Expected behaviour

It would be good if there were options to change the direction stairs face...

### Minecraft version

1.20

**Comment by Hortseen** [comment]
You actually can, use the pattern picker and select a stair in a different orientation and it will be able to fill with that different block state
