### ISSUE TITLE
dark_prismarine_slabs isnt an option?

### ISSUE THREAD

**Issue by brotai** [SIsilicon/WorldEdit-BE#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

not able to change blocks to/from dark prismarine slabs.

### Expected behaviour

NOTE: Might be a bug from the actual game, as I can't /give @s dark_prismarine_slab or prismarine_slab either ( I tried every variation of prismarine slab.)

However, using these in the commands work: "dark_prismarine_stairs" for dark prismarine stairs, and "prismarine_block" for dark prismarine blocks.

### Minecraft version

1.20.0

**Comment by SIsilicon** [comment]
Since dark prismarine is a _variation_ of prismarine, you have to define its block state as well. So either `prismarine[prismarine_block_type=dark]` or `prismarine:1`.
