### ISSUE TITLE
0.9.0.3 is Incompatible with 1.20.80.23

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Nothing works or loads

### Expected behaviour

Everything works as expected

### Steps to reproduce

Try using world edit in the latest preview

### Minecraft version

1.20.80.23

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/238
