### ISSUE TITLE
Not working on 1.20.72

### ISSUE THREAD

**Issue by ProCool2184** [SIsilicon/WorldEdit-BE#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The tag command doesn't work and ; kit and every command and item 

### Expected behaviour

The tag command must work and ; kit and every command and item 

### Minecraft version

1.20.72

### Device and operating system

Xbox series s

**Comment by SIsilicon** [comment]
Practically a duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/241
