### ISSUE TITLE
;kit command is missing some of the tools.

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When using the ;kit command, you get the majority of world edit's tools but some of them are left out and can only be found through using commands and sleuthing them out. This hinders the flexibility of the mod as alot of cool stuff people can use they might not know is in the mod off rip. or at all. Adding them to the creative inventory aswell like the pattern picker & mask picker would help this even more.

### Expected behaviour

All the tools in world edit are given upon using the ;kit command.

### Steps to reproduce

Use the ;kit command

### Minecraft version

<1.20.80.24

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
WorldEdit 0.8.6 won't work in 1.20.80. Wait until WorldEdit 0.8.7 is released or use the latest beta add-on.

**Comment by Hortseen** [comment]
That's not what the issue is, you get the tools, the mod fully works. But the command doesn't give you ALL the world edit tool items
