### ISSUE TITLE
Brushes Do Not Have Outlines in 0.9.0.4/5

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When using a brush in the latest update, outlines will not be drawn to preview the affected area. This works for tools, just not brushes. The draw outlines setting is turned on btw.

### Expected behaviour

Brushes show outline selection shapes.

### Steps to reproduce

Make a brush, hover over an area and try to find the selection area. Then try with the wand and you'll see tools work but not brushes

### Minecraft version

1.20.80.24

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Fixed with commit https://github.com/SIsilicon/WorldEdit-BE/commit/51ad2680589592ab20724e6cef533f290f69138b
