### ISSUE TITLE
Undo Doesn't Work on Block Replacer Tool (0.9.0.4)

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When trying to undo edits made with the block replacer tool, world edit doesn't touch what you did at all with that tool and will instead undo edits made without the tool, Making development more tedious.

### Expected behaviour

The undo & redo actions correctly work for the block replacer tool.

### Steps to reproduce

1. Make a new block replacer tool.
2. Make sure you have the undo item in your inventory.
3. Replace a block with the block replacer tool.
4. Try to undo that action.

### Minecraft version

1.20.80.24

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
This is intentional since the replacer tool can make a large amount of individual edits at a time.
