### ISSUE TITLE
0.9.0.4 is Incompatible With 1.21.0.20

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Worldedit is broken

### Expected behaviour

Worldedit works

### Steps to reproduce

Try anything worldedit related in the latest preview (1.21.0.20) on 0.9.0.4

### Minecraft version

1.21.0.20

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Yeah the script API changed between then and now. 0.9.0.5 will work when released

**Comment by Hortseen** [comment]
Thank you so much for all the effort you pour into this mod. You're doing the lord's work, and I'm an Athiest:)
