### ISSUE TITLE
Smooth Brushes Don’t Work For Ceilings 0.9.0.5

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Using the smooth brush/commands on ceilings doesn’t smooth anything, and if it does, it’s a very very small portion and leaves everything else rough.

### Expected behaviour

The smooth tool/command should smooth ceilings with the same level of parity as terrain floors

### Steps to reproduce

Make and use a smooth brush/command on a cave ceiling. 

### Content logs

None

### Minecraft version

1.21.0.21

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
This is expected. The smooth brush can only smooth the height of terrain. If you want something more all-purpose, use the erosion brush in "smooth" mode.

**Comment by Hortseen** [comment]
That isn't an option in the configuration menu
