### ISSUE TITLE
A lot of scripts are broken in 0.9.0.5 on 1.21.0.23

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

A lot of the scripts are broken in this version

### Expected behaviour

Everything works correctly

### Steps to reproduce

Try using all aspects of world edit

### Minecraft version

1.21.0.23

### Device and operating system

Windows 11

**Comment by CrackedMatter** [comment]
Can you give some examples?

**Comment by Hortseen** [comment]
Making a brush or tool freezes your inventory and you cannot pick any item to bind it to and the selection item in the hotbar isn't present. The world edit wand will try the fill tool gets stuck at 50% for generating blocks forever and the copy and paste tools don't work at all
