### ISSUE TITLE
0.9.0.5 is Incompatible With 1.21.0.24

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

World edit doesn’t load

### Expected behaviour

World edit works

### Steps to reproduce

Try anything, like the ;kit command for example

### Minecraft version

1.21.0.24

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
There've been some API changes so another beta is needed

**Comment by SIsilicon** [comment]
Closing since a new beta is available to resolve this
