### ISSUE TITLE
Block Parameters For fill/replace

### ISSUE THREAD

**Issue by USBMenus** [SIsilicon/WorldEdit-BE#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

not sure if this would be a bug or enhancement but arguments can not be set for the blocks in the mask or pattern
ex. `dirt["dirt_type"="coarse"]`
![image](https://github.com/SIsilicon/WorldEdit-BE/assets/69381115/c297c43b-16c3-4a66-a2e3-0c1cd1959643)

### Proposed Solution

add the option for block arguments or add each block that needs the arguments with a new id

**Comment by SIsilicon** [comment]
This looks more like a bug than a suggestion. Closing this. Make a bug report with more detail if you're still having problems
