### ISSUE TITLE
Block State Parameters For Fill/Replace

### ISSUE THREAD

**Issue by USBMenus** [SIsilicon/WorldEdit-BE#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Block state parameters can not be used in fill/replace commands, i would assume its the same for all the commands using block operations
These are a few examples:
`dirt["dirt_type"="coarse"]`, `torch["torch_facing_direction"="unknown"]`, `oak_stairs["upside_down_bit"=true]`

I receive a parsing error
![image](https://github.com/SIsilicon/WorldEdit-BE/assets/69381115/0674245a-60f5-4970-90ff-c6885bfa309f)

### Expected behaviour

I expect to be able to use block state parameters when doing block operations

### Steps to reproduce

1. Select Positions 1 and 2
2. Try filling or replacing using block state parameters, ex.`;replace grass dirt["dirt_type"="coarse"]`
3. Receive a parsing error

### Minecraft version

1.20.81

### Device and operating system

Windows 10

**Comment by CrackedMatter** [comment]
Omit the quotation marks

**Comment by USBMenus** [comment]
> Omit the quotation marks

thank you
