### ISSUE TITLE
0.9.0.6 Isn’t Compatible With API Changea In 1.21.10.20

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

World edit isn’t compatible with the latest preview (1.21.10.20)

### Expected behaviour

World edit it upto speed

### Steps to reproduce

Try using Worldedit in the latest preview

### Minecraft version

1.21.10.20

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Expected. Would have to release another version for 1.20.10
