### ISSUE TITLE
[BUG] Setting item's tools drop roughly 15 seconds after using "Back" tool

### ISSUE THREAD

**Issue by iBryguy** [SIsilicon/WorldEdit-BE#27]
**Description** 
After using the Setting item's "Back" tool to return to normal inventory, the individual setting tools drop at the location the user used the "Back" tool.

**Steps to reproduce** 
1. Use the wooden pickaxe to add the individual tools to hotbar. 
2. Use the Settings tool.
3. Use the "Back" tool.
4. Wait ~15 seconds. (Possibly upwards of 20 seconds).

**Expected behavior** 
No items drop.

**Screenshots**

[Image of items floating after dropping from original player location when "Back" tool was used.](https://imgur.com/a/1E9HAqz)

**Content logs**

N/A.

**Minecraft version** 
1.17.41

**Device and operating system**
PC, Windows 10.

**Additional info**

**Comment by PlushBanshee** [comment]
how do you get the tools what command did you use all i can get is the selection axe

**Comment by SIsilicon** [comment]
`;help navwand`
`;help tool`
