### ISSUE TITLE
Bring back the rotate & flip tools!

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

The new implementation of crouching to make a change with the paste tool is so much slower and annoying to use. It’s more tedious when you’re flying, you can’t re-open the menu after making one adjustment & several usecases aren’t supported by the new crouching menu. It’s a much bigger headache and was really unnecessary. Please revert that change. Bring back the dedicated rotate clockwise/counterclockwise & flip tools. 

### Proposed Solution

Bring back the dedicated rotate clockwise, rotate counter-clockwise & flip tools

**Comment by YairsitOwO** [comment]
I agree with this comment; it's very tedious to change the direction of constructions while flying, and it also takes longer. The tools that were available before (to change direction clockwise and counterclockwise, as well as to flip) are much easier and more practical to use.

**Comment by SIsilicon** [comment]
I hear you. Reverted in https://github.com/SIsilicon/WorldEdit-BE/commit/e0d2db09733d2a3a5e64648ef5241a6f542271dc
