### ISSUE TITLE
The download link doesn't work

### ISSUE THREAD

**Issue by DeezWat** [SIsilicon/WorldEdit-BE#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The download link doesn't work

### Expected behaviour

The download link work

### Steps to reproduce

1. I click the download link from mcpedl
2. The link goes to https://lootlinks.co/s?cFwI
3. Then I click "read interesting articles"
4. Then the link goes to https://api.airfind.com/link/v1?id=6642452d8c144769955fcf34&clientId=51273&brand=ID_mobile_fall&unique_req=442635247629355868  then I click "Watch a video"
5. Then the link goes to https://free-games.io/?brand=ID_mobile_fall  Then I wait and play for couple minutes but when I comeback it's still not have the link download

### Minecraft version

1.21.0.03

### Additional info

![Screenshot_2024-06-18-23-31-31-18_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/SIsilicon/WorldEdit-BE/assets/173180552/e2ad7597-ff52-4476-835f-90052b2f8595)

**Comment by captaindopesauce** [comment]
You can download the latest release from the github [release section](https://github.com/SIsilicon/WorldEdit-BE/releases) directly.

I would suggest that any errors regarding download from mcpedl's website, including all of the download setps required is an error with their website and download link.
