### ISSUE TITLE
A requesting invalid module version for [@minecraft/server-ui - 1.2.0-beta] and [@minecraft/server - 1.12.0-beta].

### ISSUE THREAD

**Issue by ReazonGd** [SIsilicon/WorldEdit-BE#277]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

maybe this is the same problem as "WorldEdit tag not working". adding worldedit tag doesn't respond anything. as well as using commands. 

### Expected behaviour

changing the versions of dependencies module @minecraft/server to 1.14.0-beta and @minecraft/server-ui to 1.2.0 in manifest.json fixed this issue. I tried to use @minecraft/server version 1.12.0 but the problem of failing to export WatchdogTerminateReason appeared. maybe it's not in this version?

### Content logs

```
10:17:15[Scripting][error]-Plugin [WorldEdit Bedrock Edition 0.9.0] - module [WorldEdit Bedrock Edition 0.9.0 - 1.0.0] requesting invalid module version [@minecraft/server-ui - 1.2.0-beta].
Available versions:
@minecraft/server-ui - 0.1.0
@minecraft/server-ui - 1.0.0
@minecraft/server-ui - 1.1.0
@minecraft/server-ui - 1.2.0
@minecraft/server-ui - 1.3.0-beta
@minecraft/server-ui - 2.0.0-alpha


10:17:15[Scripting][error]-Plugin [WorldEdit Bedrock Edition 0.9.0] - module [WorldEdit Bedrock Edition 0.9.0 - 1.0.0] requesting invalid module version [@minecraft/server - 1.12.0-beta].
Available versions:
@minecraft/server - 0.1.0
@minecraft/server - 1.0.0
@minecraft/server - 1.1.0
@minecraft/server - 1.2.0
@minecraft/server - 1.3.0
@minecraft/server - 1.4.0
@minecraft/server - 1.5.0
@minecraft/server - 1.6.0
@minecraft/server - 1.7.0
@minecraft/server - 1.8.0
@minecraft/server - 1.9.0
@minecraft/server - 1.10.0
@minecraft/server - 1.11.0
@minecraft/server - 1.12.0
@minecraft/server - 1.13.0
@minecraft/server - 2.0.0-alpha
@minecraft/server - 1.14.0-beta
```

### Minecraft version

1.21.20 

### Device and operating system

Android 13

### Additional info

*how i fix*
- open manifest.json (BP).
- change the ` @minecraft/server` to `1.14.0-beta` or latest version. ( in mc 1.21.30 beta, try 1.15.0-beta )
- chage the ` @minecraft/server-ui` to `1.2.0` or latest

i hope it will help.

**Comment by josephdpurcell** [comment]
Thank you for documenting this! I made the change as described in "how i fix" and worldedit started working again.

I'm on worldedit 0.9.0. I see there is a 0.9.1 release which has this in the manifest for the BP:

```json
    "dependencies": [
        {
            "module_name": "@minecraft/server",
            "version": "1.14.0-beta"
        },
        {
            "module_name": "@minecraft/server-ui",
            "version": "1.3.0-beta"
        },
```

and based on that I would assume that another way to fix worldedit is just to upgrade from 0.9.0 to 0.9.1 (or higher).

**Comment by ReazonGd** [comment]
i read the documentation again and the "WatchdogTerminateReason" now in 1.15.0-beta. but maybe for next mc update. so, thanks for the upade!

**Comment by Aevarkan** [comment]
Hi there, good effort in dealing with that problem yourself!

That "requesting invalid module version" error was quite common when the game updated. It's something we definitely know about, because it was a chore to do every update.

Thankfully, creators can now put `beta` in the version field, which saves a lot of hassle. Things will still break when the APIs themselves change, but they'll no longer need to be updated nearly as often.

Here is what exists now:
https://github.com/SIsilicon/WorldEdit-BE/blob/54fb1ea2396f8b4031cffef55d62c73462473635/mc_manifest.json#L42-L69
