### ISSUE TITLE
[BUG] Using the ;help command, without page reference, leads to page NaN of 8.

### ISSUE THREAD

**Issue by iBryguy** [SIsilicon/WorldEdit-BE#28]
**Description** 

If you use the command `;help`, it takes you to help page NaN of 8.

Similarly, although tangentially related, using a help page of 0 or less returns a TypeError in chat as read property '0' is undefined.

**Steps to reproduce** 
1. Open chat.
2. Use command `;help`
3. See error.

**Expected behavior** 
Expected that the help page 1 would be displayed, as that is the first of the help pages. 
Alternatively, would have been reasonable to have been given information on either `;help <page number>` and/or `;help [command: CommandName]` and/or `;? [command: CommandName]`

**Screenshots**
[Chat message resulting from using ';help'](https://imgur.com/a/vUcvRjX)

**Content logs**
N/A.

**Minecraft version** 
1.17.41

**Device and operating system**
PC, Windows 10

**Additional info**

**Comment by SIsilicon** [comment]
`;help 1` still works though, right?

**Comment by iBryguy** [comment]
Yep, all normal help pages work appropriately. It's a minor issue overall; just thought I'd let you know about it.
