### ISSUE TITLE
How to install WorldEdit-BE on Minecraft Bedrock Server [ DOCUMENTATION ]

### ISSUE THREAD

**Issue by josephdpurcell** [SIsilicon/WorldEdit-BE#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

The existing documentation didn't explain in sufficient detail how to install WorldEdit-BE on a Minecraft Bedrock server, see https://worldedit-be-docs.readthedocs.io/en/stable/installation/. Specifically, how exactly to wire up the packs and how to enable experimental mode.

A very strong counter-argument to this being a "problem" is that wiring up packs and enabling experimental mode is out of scope for this project.

### Proposed Solution

I propose that this ticket serves as the solution? I didn't find a way to submit this as documentation, so I'm filing it as a feature request.

A detailed step-by-step guide for installing this mod on a server is written here: https://github.com/itzg/docker-minecraft-bedrock-server/discussions/442

I think this ticket existing in a searchable way that links out there is fine. I'll close this ticket after creation.

**Comment by josephdpurcell** [comment]
Closing since this is just documentation.

**Comment by Aevarkan** [comment]
Hiya @josephdpurcell, thanks for your effort in creating a [guide](https://github.com/itzg/docker-minecraft-bedrock-server/discussions/442) on how to install WorldEdit: Bedrock Edition in BDS.

If, after all this time, you are still interested in creating documentation for the wiki, you can find the repository [here](https://github.com/SIsilicon/WorldEdit-BE-Docs). Have a look at the [contribution guide](https://github.com/SIsilicon/WorldEdit-BE-Docs/blob/master/CONTRIBUTING.md) for more details.
