### ISSUE TITLE
Unable to use WorldEdit-BE on Aternos

### ISSUE THREAD

**Issue by Ascension233** [SIsilicon/WorldEdit-BE#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

To install the small wooden axe on the server, you need to add variablejson to the config/default folder. However, Aternos does not have write file permission to the config/default folder, and adding files will prompt access denied

### Expected behaviour

Successfully used WorldeditBE in Aternos

### Steps to reproduce

1.Download Worldeditbe server. zip
2.Enable experimental mode and enable the required options
3.Import worldeditBP and worldeditRP into the packs folder
4.Import the variable. json in the config/default folder, prompting access denied :-(

### Content logs

[2024-08-16 14:46:54:227 ERROR] [Scripting] Plugin [WorldEdit Bedrock Edition 0.9.0 - 1.0.0] - does not contain main file [server/index.js].

### Minecraft version

1.21.2 and the WorldeditBE v0.9.0

### Device and operating system

Windows 10

### Additional info

![04fa1af171666ca8d2912d5edaa08599](https://github.com/user-attachments/assets/7411d8f7-4b7b-4600-87dc-5b0b78c7870e)
![368e25578458ba170b4c173372b24ac4](https://github.com/user-attachments/assets/620cad50-2abc-4892-98c5-6681992b5eed)
![f859949f5dc1bb54c897b743193c513c](https://github.com/user-attachments/assets/5ce9f0a0-a47b-4db4-b4a7-e5865a29235d)

**Comment by SIsilicon** [comment]
Yes, Aternos doesn't like the server version of the add-on ironically. you have to use the normal version instead
