### ISSUE TITLE
Download links for release versions only downloads an outdated version

### ISSUE THREAD

**Issue by RhymerJ123** [SIsilicon/WorldEdit-BE#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

All download links I have tried for version 9.0.1 have downloaded the 0.8.7 .mcaddon file instead. I have noticed, however, that links for pre-release versions download the file for that exact pre-release version and not 0.8.7. 

### Expected behaviour

Expected behavior is that the right .mcaddon file is downloaded.

### Minecraft version

1.21.21

### Device and operating system

iOS

**Comment by raphifou9992** [comment]
Well it seems like thats fixed :/
