### ISSUE TITLE
tools dont behave as expected

### ISSUE THREAD

**Issue by theonlytruemuck** [SIsilicon/WorldEdit-BE#296]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

when i used the move command ";move -s 1" it moved the blocks in the selection box and the selection box one block but when i tried making a tool ";tool cmd ;move -s 1" it just said s is an invalid argument and didnt modify the tool.

### Expected behaviour

it should have made a tool that when used moves the blocks in the selection box and the selection box one block into the direction im looking at

### Minecraft version

1.21.30

### Device and operating system

samsung galaxy A25

### Additional info

i dont know if it is related in any way i also have canopy and undersdudy installed. maybe they are conflicting in any way

**Comment by CrackedMatter** [comment]
You need to wrap the command in quotes: `;tool cmd ";move -s 1"`

**Comment by theonlytruemuck** [comment]
o thank you
