### ISSUE TITLE
New Particles Don’t Work

### ISSUE THREAD

**Issue by Hortseen** [SIsilicon/WorldEdit-BE#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The new particle system you made earlier doesn’t work in 1.21.41 with world edit version 9.3

### Expected behaviour

The new particle system works, it is a way more beautiful way of displaying selection zones

### Steps to reproduce

Make a selection with the wand

### Minecraft version

1.21.41

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment]
Those particles were removed for internal reasons
