### ISSUE TITLE
Says 'You don't have the permission to execute this command' when type ';help

### ISSUE THREAD

**Issue by PaperSoft** [SIsilicon/WorldEdit-BE#30]
**Description** 
I was trying to use this addon but when i typed ';help' or ';pos1', it said 
'You don't have the permission to execute this command'

**Steps to reproduce** 

**Expected behavior** 
I expected it will work well.
**Screenshots**
![Uploading image.png…]()

**Content logs**
I don't see any
**Minecraft version** 
1.18
**Device and operating system**
LG Gram
Windows 11
**Additional info**

**Comment by PaperSoft** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/72278360/144677783-94aa42b0-71f5-4f24-bc57-d40143e4d15f.png">
I think the image didn't uploaded well so uploading it here

**Comment by SIsilicon** [comment]
You have to give yourself permission first.
Please read quick start in [the docs](https://worldedit-be-docs.readthedocs.io/en/latest/?badge=latest) for a tutorial.

**Comment by SIsilicon** [comment]
@PaperSoft Is it working for you now?

**Comment by PaperSoft** [comment]
oh I see it works well now sorry for not reading the docs
thank you

**Comment by PaperSoft** [comment]
also how do I use ;stack command?
