### ISSUE TITLE
Tools and brushes disappear when connecting to the world

### ISSUE THREAD

**Issue by MrCrystalc** [SIsilicon/WorldEdit-BE#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When you create new tools or brushes, they are active only while you are playing in the world, after switching to this world, tools and brushes disappear. I tried to create in a new world, but it don't work. Developer features and beta API are enabled. 
P.s it is also noticed that gradients and changed worldedit settings disappear. Mod version 0.9.3

### Expected behaviour

So that when you enter the world, tools and brushes, they remain working. and you wouldn't have to create tools and brushes 12 times

### Steps to reproduce

1. creating new tools or brushes 
2. checking their performance (using) 
3. leaving the world 
4. joining the world
5. those tools and brushes are no more 

### Minecraft version

1.21.41.01

### Device and operating system

Android / smartphone

### Additional info

Video of the bug (shown in the example) - https://youtu.be/XWvmHEAe3Z0

**Comment by SIsilicon** [comment]
The downloads have been updated to fix this issue. If nothing else it's fixed in the next update, 0.9.4

**Comment by MrCrystalc** [comment]
> Загрузки были обновлены, чтобы исправить эту проблему. Если ничего другого, это будет исправлено в следующем обновлении, 0.9.4

Thank you
