### ISSUE TITLE
*Dont work*

### ISSUE THREAD

**Issue by Mincescraft** [SIsilicon/WorldEdit-BE#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

when I type "/tag @s add worldedit" it works... but when I next type ";kit" nothing happens, ABSOLUTELY NOTHING! (I activated the "beta APIs")

### Expected behaviour

I hoped I would receive my items, and start building! but no item appeared in my hotbar

### Steps to reproduce

I download the mod, export it to Minecraft, activate and enable the features/behaviors, enter the game, write "/tag @s add worldedit", look at the tips and instructions in the addon menu, and when I write ";kit" to receive my item kit... I get nothing

### Minecraft version

1.21.44

### Device and operating system

Windows 11

### Additional info

![image](https://github.com/user-attachments/assets/ddd3476c-4210-4495-a28d-6766649477e9)
![Captura de tela 2024-11-03 160031](https://github.com/user-attachments/assets/0a40fc2f-c53c-4dff-aa66-c47a4e0aa5f5)

**Comment by Mincescraft** [comment]
see?

**Comment by SIsilicon** [comment]
See https://github.com/SIsilicon/WorldEdit-BE/issues/134. Maybe something in that issue could help you. I notice that this is a problem for some people but it's not something I can reproduce on my end

**Comment by Mincescraft** [comment]
But my problem is still not solved! How did I get like this?

Em seg., 2 de dez. de 2024 01:04, Roujel Williams ***@***.***>
escreveu:
