### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by ZeroWillToLiv3** [SIsilicon/WorldEdit-BE#304]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

A couple months ago I downloaded this mod and had little problems like missing tools that I made do with. I took a break from the mod for a month. Came back to play with it again with the intention of fixing the missing tool issue. I got rid of a texture pack that I used with the mod. This is when the commands stopped working. In the new world, I did all of the proper steps to set it up, but the commands weren't working. I thought I would have been able to fix this through redownloading the mod just in case of an update. I did just that. Did not work once again. I restarted Minecraft, did /reload, and deleted all of the mods that I had in my downloads, but it just didn't work. This is starting to really bother me because I was working on a project and this mod really helped speed up the process. I've tried to look for alternatives, but they provide vague instructions for downloading or are outdated. I don't want to rush you but I really enjoy this mod. So please, fix this issue.

### Expected behaviour

I expected the commands to work after putting the mod on a new world.

### Minecraft version

1.21.44

### Device and operating system

Xbox Series S

**Comment by MishMush1** [comment]
I have had this bug aswell and its really annoying because im currently doing a big project and I was hoping this was really going to speed it up

**Comment by SIsilicon** [comment]
See https://github.com/SIsilicon/WorldEdit-BE/issues/134
