### ISSUE TITLE
[BUG] Does Not Work Properly for Users with Multiple Spaces in Name (with fix)

### ISSUE THREAD

**Issue by iBryguy** [SIsilicon/WorldEdit-BE#33]
**Description** 
If a player has more than one space in their name, then this will not work properly.

**Steps to reproduce** 
1. Have a username with more than one space in it (e.g., "but me iBryguy").
2. Attempt to use tools from this program (i.e. brushes, settings, fill, copy, etc).
3. See errors in program's behavior.

**Expected behavior** 
Tool should work regardless of the user's username.

**Screenshots**
N/A

**Content logs**
N/A

**Minecraft version** 
1.18

**Device and operating system**
PC

**Additional info**
I've encountered several previous issues, and with some free time decided to attempt to find their source. After fiddling with some of the code, I found the main problem: `player.nameTag.replace(" ", "_")`.
This works sufficiently when a player has one or fewer spaces, but not if they have two or more. The fix is to replace all instances of `player.nameTag.replace(" ", "_")` with `player.nameTag.replaceAll(" ", "_");`. 

For convenience, here are all instances I've found:

In src/server/modules/region.ts
[Line 21](https://github.com/SIsilicon/WorldEdit-BE/blob/master/src/server/modules/regions.ts#L21)

In src/server/modules/player_util.ts
[Line 32](https://github.com/SIsilicon/WorldEdit-BE/blob/ace87a0178280f0db6ab5cfdb9cb653f758a2da8/src/server/modules/player_util.ts#L32)
[Line 98](https://github.com/SIsilicon/WorldEdit-BE/blob/ace87a0178280f0db6ab5cfdb9cb653f758a2da8/src/server/modules/player_util.ts#L98)
[Line 147](https://github.com/SIsilicon/WorldEdit-BE/blob/ace87a0178280f0db6ab5cfdb9cb653f758a2da8/src/server/modules/player_util.ts#L147)
[Line 161](https://github.com/SIsilicon/WorldEdit-BE/blob/ace87a0178280f0db6ab5cfdb9cb653f758a2da8/src/server/modules/player_util.ts#L161)
[Line 179](https://github.com/SIsilicon/WorldEdit-BE/blob/ace87a0178280f0db6ab5cfdb9cb653f758a2da8/src/server/modules/player_util.ts#L179)

**Comment by iBryguy** [comment]
I do want to add: from testing this fix with the files I'm using, using `replaceAll` in these lines does also fix the following issues I'd reported previously:

- [Setting item's tools drop roughly 15 seconds after using "Back" tool](https://github.com/SIsilicon/WorldEdit-BE/issues/27)
- [Settting item's individual settings tools do not work if player has moved](https://github.com/SIsilicon/WorldEdit-BE/issues/26)
- [TypeError on attempted brush use](https://github.com/SIsilicon/WorldEdit-BE/issues/25)

**Comment by SIsilicon** [comment]
Yes, I've also realized that the function only replaces one space. Thanks for pointing out the places where it's used. I'll make a pull request that fixes this issue after [this one](https://github.com/SIsilicon/WorldEdit-BE/pull/32).

**Comment by SIsilicon** [comment]
Alrighty, it should be fixed now as of commit 44a74c8. Test it out to see if it works now.
