### ISSUE TITLE
History was still being recorded

### ISSUE THREAD

**Issue by GeorgitoLOL** [SIsilicon/WorldEdit-BE#34]
**Description** 

**Steps to reproduce** 

**Expected behavior** 

**Screenshots**

**Content logs**

**Minecraft version** 

**Device and operating system**

**Additional info**

**Comment by GeorgitoLOL** [comment]
I was using worldedit but then i was going to do  ;set but it said "Historiy was still being recorded"

**Comment by SIsilicon** [comment]
It could help more if you fill out the fields as required. Closing until then.
Btw, this is a known issue which is being worked on.

**Comment by SIsilicon** [comment]
@GeorgitoLOL In the meantime, this issue can be resolved for you by restarting, or reinstalling Minecraft.
