### ISSUE TITLE
[BUG] Undo sometimes does not work

### ISSUE THREAD

**Issue by Ultr4Anubis** [SIsilicon/WorldEdit-BE#49]
**Description** 
When using the addon on a world, it will randomly stop working and a message pops up every time when tying to run a command.

The message "History is still being recorded" pops up and never fixes it self. The only way to fix it is to restart the world

**Comment by SIsilicon** [comment]
This bug has happened to several people at least once, but there seems that be no way to easily replicate it.

**Comment by SIsilicon** [comment]
So upon closer inspection, it _looks_like a problem with saving and loading structures. More info needed to confirm.

**Comment by SIsilicon** [comment]
So far, no confirmation as to whether this still happens. Closing for now.

**Comment by SIsilicon** [comment]
The error seems to happen still, but it takes on a different form.
Undo not being defined or something.

**Comment by wow1972** [comment]
Red text is printed when you undo.

**Comment by wow1972** [comment]
Please fix this bug quickly

**Comment by SIsilicon** [comment]
Attempted fix in f320ce9570902039fb4667be3ffd39baf9144ef5.
If this still happens, say so to reopen this issue.
