### ISSUE TITLE
Cannot place a block at pos1 and pos2 after running several commands. And the addon breaks also.

### ISSUE THREAD

**Issue by Fuzlop** [SIsilicon/WorldEdit-BE#5]
I used ;set air command to clear area, everything worked fine at the first few times but after 2-3 times of executing the command the system gets weird. Commands don't work anymore and selection area doesn't glow with particle. And can't place anything at the exact points that i set as pos1 and 2. Gravel and sand can be placed to the point via gravity and entities like torches also can be but none of full blocks. I couldn't find the way to make the corrupted worlds back to normal without removing the addon, they remains corrupted despite of reloading or doing anything.

It gives some error messages when i try to run a command .. if I remember right they're like below
<Script Engine> Script Engine whispers to you: Failed to get property 'nameTag'
or
<Script Engine> Script Engine whispers to you: Failed to find request (?) I am not sure about this one.

Used version is 1.17.40 but same happened in 1.17.34
And it happened multiple times in multiple worlds, without any other addon, or with other addons

**Comment by SIsilicon** [comment]
Closing due to lack of support
