### ISSUE TITLE
better sphere generator

### ISSUE THREAD

**Issue by Minatocraft** [SIsilicon/WorldEdit-BE#51]
Generating a large sphere causes the game to crash . I suggest that the sphere generate in batches just like [this addon](https://mcpedl.com/worldedit-addon/)

**Comment by SIsilicon** [comment]
The game doesn't crash from large spheres. It just freezes for a long time because of how large the sphere is. It also depends on the performance of the device.

**Comment by SIsilicon** [comment]
Closing as current method has been tested to be faster than the one proposed.
