### ISSUE TITLE
Unable to replace with coloured stained-glass

### ISSUE THREAD

**Issue by thecrazy** [SIsilicon/WorldEdit-BE#56]
I selected glass block with the axe (pos 1 and 2) 
When I try to replace the blocks with other blocks or even stained_glass, it works fine.
When trying to replace with a coloured stained-glass i.e.: light_blue_stained_glass OR red_stained_glass it doesn't, none of the coloured stained-glass appears to work.

There is no error it just says: 0 blocks have been changed.

**Comment by SIsilicon** [comment]
Expected behaviour.
Please read the faq section in the docs for how to make coloured blocks.
https://worldedit-be-docs.readthedocs.io/en/stable/common_questions/
