### ISSUE TITLE
please add ;line to make lines. and ;fill

### ISSUE THREAD

**Issue by IronSmithMC** [SIsilicon/WorldEdit-BE#60]
**Is your feature request related to a problem? Please describe.**
no not a problem. just wanting //line and //fill but with the addon

**Describe the solution you'd like**
idk im not a programmer. i just want ;line and ;fill LOL

**Describe alternatives you've considered**
there arent any. this is the best world edit addon ive ever seen

**Additional context** 
idk

**Comment by SIsilicon** [comment]
There's already a feature request open for the line command. https://github.com/SIsilicon/WorldEdit-BE/issues/54
And for ;fill, what you're looking for is actually called the ;set command.
