### ISSUE TITLE
[BUG] Game crashes when selecting a custom block as a pattern

### ISSUE THREAD

**Issue by thecrazy** [SIsilicon/WorldEdit-BE#67]
**Description** 
Game crashes when selecting a custom glass block as a pattern

**Steps to reproduce** 

**Expected behavior** 
Your game doesn't crash

**Screenshots**
https://i.ytimg.com/vi/2mH0wKvIThc/hqdefault.jpg
(kidding, there is nothing to see)

**Content logs**
null

**Minecraft version** 
1.18.12

**Device and operating system**
Windows 10

**Additional info**
I love what you did with the place.

**Comment by SIsilicon** [comment]
This is due to a bug with the Gametest framework. Until this is resolved, the only workaround would be to disable the ability to analyse or manipulate custom block properties.

**Comment by thecrazy** [comment]
Mmm, how about a list of blocks that are to be ignored by WorldEdit?

I'm sure servers would benefit from being able to block people from
spawning walls of TNT or some other blocks.

It could also prevent the deletion of certain blocks.

All that while preventing the server from crashing on certain custom blocks.

**Comment by SIsilicon** [comment]
Closing as this no longer happens
