### ISSUE TITLE
[BUG] Game shows an error under zh-cn language

### ISSUE THREAD

**Issue by smallg0at** [SIsilicon/WorldEdit-BE#68]
**Description** 

At Launch, Minecraft shows the following message:
[Localization][warning]-Line: 200 - Invalid lang file format. New line character was found while parsing key: '§ehttps://worldedit-be-docs.readthedocs.io§r'.

**Steps to reproduce** 
1. Set game language to Chinese (Simplified)
2. Restart Minecraft

**Expected behavior** 

No error should appear

**Screenshots**

![image](https://user-images.githubusercontent.com/30719670/154492046-5d6b0290-ea56-459e-ba37-48a1ef1ea979.png)

**Minecraft version** 

1.18.12

**Device and operating system**

Windows 11 Build 22543

**Comment by SIsilicon** [comment]
Fixed in the translation files. There was \n in Chezk
