### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by MyKidIsBroken** [SIsilicon/WorldEdit-BE#7]
I installed this mod today and i did everything right with enabling the mod BE and RE and activating the experimental options but after I load it in a world, and do /tag @s add builder , it doesn't do anything but I'm sure it adds me as a builder cuz if I do it again it says I'm already, I do ;wand and doesn't do anything, and even if I do /give and give myself the navigation and select wand, they don't do anything 

Im running version 1.17.40 on windows 10

**Comment by SIsilicon** [comment]
@ItsMazenWWE Did you have a space in your player name?

**Comment by SIsilicon** [comment]
Closing due to lack of support.
