### ISSUE TITLE
select large areas cause the game to crush or lag

### ISSUE THREAD

**Issue by Minatocraft** [SIsilicon/WorldEdit-BE#71]
**𝗘𝘃𝗶𝗹𝗸𝗶𝗹𝗹𝗲𝗿𝟯𝟮𝟭: "i think you should make selections clear itself once you 700blocks away from the selected areas bec i keep forgetting to do ;sel then for example i teleport 1000 blocks away then i select a new area but then it crashes my entire pc then i gotta restart it"**
or you can just add a limit to the selection and a message telling the user that the selected area is too large.

**Comment by SIsilicon** [comment]
Fixed in the latest commits!
