### ISSUE TITLE
[REQUEST] (Deselect air block)

### ISSUE THREAD

**Issue by Ultr4Anubis** [SIsilicon/WorldEdit-BE#73]
When copying and pasting a region, all the air blocks get copied and pasted as well. When trying to move one thing to another place, sometimes the air blocks end up destroying the surrounding builds.

It would be awesome if there was a way to filter out the air blocks from selections as they can be annoying.

**Comment by SIsilicon** [comment]
Can already be done.
By command add the -a flag.
By kit, go to config item and toggle "include air in selection".
