### ISSUE TITLE
[REQUEST] An option to clear the mask

### ISSUE THREAD

**Issue by Tree05** [SIsilicon/WorldEdit-BE#81]
**Is your feature request related to a problem? Please describe.**

I set a mask to fill part of an area, then I tried to clear the mask to fill another area, but I couldn't find a way to do it.

**Describe the solution you'd like**

A way to get rid of the current mask, not just the global mask.

**Describe alternatives you've considered**

Being able to use a command like `;mask none` or `;mask clear` to get rid of the mask.

**Comment by SIsilicon** [comment]
@Tree05 The mask picker uses the global mask, so running `;gmask` without any arguments will clear said mask.
