### ISSUE TITLE
[REQUEST/BUG] - ;flip, ;set, ;replace

### ISSUE THREAD

**Issue by CheckURMSG** [SIsilicon/WorldEdit-BE#82]
Hi!
The flip command is missing the up / down function. At least I couldn't find a way to flip up a selected area. This makes it impossible to create a floating island, for example.
One more thing. Some new types of stairs cannot be created/replaced in all directions. ;set deepslate_brick_stairs:1 = deepslate_brick_stairs:2 = :3 = :4 etc.

**Comment by SIsilicon** [comment]
Better ;flip support has been added as of commit https://github.com/SIsilicon/WorldEdit-BE/commit/c93798953d822c314d3f637a679c7553b18d95ec.
