### ISSUE TITLE
[REQUEST] What does "<pattern>" in user doc means?

### ISSUE THREAD

**Issue by cugfzx** [SIsilicon/WorldEdit-BE#84]
What does "\<pattern>" in user doc means?

For example, The command of generating a hollow cylinder is ";hcyl [-r] \<pattern> \<radii> [height]"

What exactly does the  "\<pattern>" mean?

**Comment by SIsilicon** [comment]
If you keep searching the docs you'll find out. One of pages are even called "pattern"

**Comment by SIsilicon** [comment]
Closing as third isn't an issue with WorldEdit.

**Comment by SIsilicon** [comment]
If you have any mute trouble with what you read in the docs, join the addon's discord server to ask questions.
