### ISSUE TITLE
[REQUEST] Make an Item for deselecting the selected area

### ISSUE THREAD

**Issue by PastEquation922** [SIsilicon/WorldEdit-BE#88]
So, I have a skygen and I use world edit to make new islands. I use the ;kit command to get all the tool items. But I have to always type a command to deselect. Please include an Item in the kit to deselect easily. thank you.

**Comment by PungentZeus0** [comment]
Too add to this, for those who prefer a more traditional WE experience, but still fine typing the whole command too time-consuming, you could also add a abbreviated version of the `;deselect` command (similar to `**;?**` for `;help`). Perhaps `;dsel` could suffice for this specific alternative.

**Comment by SIsilicon** [comment]
@PungentZeus0 both `;desel` and `;sel` are existing aliases of `;deselect`.

**Comment by SIsilicon** [comment]
You can now do `;tool cmd ;desel` to bind a tool to clear selections.
