### ISSUE TITLE
Nothing changes when using it

### ISSUE THREAD

**Issue by NoobPJJason** [SIsilicon/WorldEdit-BE#93]
So I am like making this skyblock world thingy but when i use the worldedit wand to turn stuff to air and then leave and rejoin the game nothing changed and everything went back to normal

I do use another mod for other worldedit thing but couldnt find the page and thus not the bug reports for that please anyone let me know if its just my world or the mod!

**Comment by NoobPJJason** [comment]
Here is an additional video:
https://user-images.githubusercontent.com/87309270/174477915-7f3fee9b-a4ca-42b3-9ccb-7d8bf35d7fa0.mp4

**Comment by MCAlexisYT** [comment]
@SIsilicon You forgot to close this issue

**Comment by SIsilicon** [comment]
I was waiting on your response but ok.

**Comment by NoobPJJason** [comment]
if else i did this in this like void world template someone created but i have moved on iwth that world and started a new skyblock world
