### ISSUE TITLE
Is it possible to stack without air?

### ISSUE THREAD

**Issue by kryllyxofficial01** [SIsilicon/WorldEdit-BE#94]
In the copy command, you are able to use the flag `-a`, which means air is not included in the copied blocks. Are you able to do the same in stacking as well?

**Comment by SIsilicon** [comment]
No, you currently cannot stack without including air.

**Comment by kryllyxofficial01** [comment]
Is there any chance this could be a possible feature in the future?

**Comment by SIsilicon** [comment]
https://github.com/SIsilicon/WorldEdit-BE/issues/128

**Comment by SIsilicon** [comment]
Implemented as of 0.7.1.
