### ISSUE TITLE
[BUG] Some feature broken in the nether / the end

### ISSUE THREAD

**Issue by smallg0at** [SIsilicon/WorldEdit-BE#95]
## Description 

Some crucial features does not work properly in nether and the end.

- coordinates persists between dimensions (e.g. selection zones present in the nether will show up in the main world)
    - Simple misclicks may result in a large section of the world demolished
- Filling (with tool and with `;set`) does not work most of the time.
- `;move` does not "cut" the block but will instead show "copy" behaviour

## **Steps to reproduce** 
Enter nether / end, and try them.

## **Expected behavior** 

All of those behave the same as in the overworld.

## **Content logs**

The log shows no notable exceptions, and the only warning message is basically copies of this:
```
10:04:42[Scripting][warning]-[WARN] [02:04:42 AM] A ticking area could not be created for job # 2
```

## Misc

**Minecraft version**  1.19.2

**Device and operating system** Windows 11, build 25145

This is the actual issue for #87.

**Comment by SIsilicon** [comment]
Should now be fixed in https://github.com/SIsilicon/WorldEdit-BE/commit/045f82bb6189d2f8ef649e9a571bf90eb6257659.
