### ISSUE TITLE
[BUG] (Cannot modify Unloaded chunk!)

### ISSUE THREAD

**Issue by LIVEGUYS** [SIsilicon/WorldEdit-BE#96]
My bug is like
When I just do /replace log sand it's just
Shows on the global chat 
Cannot modify unloaded chunks!
Can you pls fix that you think it's like you didn't load the chunk but I loaded every chunk on the area I wanted to replace 
Than also doesn't work still..
By youtuber
@liveguysYT

**Comment by SIsilicon** [comment]
That's not what loaded chunk means in that regard. Please read the FAQ for what the error actually means, and how to prevent it.
https://worldedit-be-docs.readthedocs.io/en/stable/common_questions/#why-does-the-message-cannot-modify-unloaded-chunks-show
